/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../../../index.js";

export interface NutritionDeleteResponse {
    user?: Terra.TerraUser;
    processed_data?: NutritionDeleteResponse.ProcessedData.Item[];
}

export namespace NutritionDeleteResponse {
    export type ProcessedData = ProcessedData.Item[];

    export namespace ProcessedData {
        export interface Item {
            /** Identifier of the nutrition log whose deletion was attempted */
            id?: string;
            /** Response code from the provider when attempting to delete the nutrition log */
            response_code?: number;
        }
    }
}
