/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UserModifyUserRequest {
    /** Identifier on your system to associate with this user */
    reference_id?: string;
    /** Whether the user should remain active */
    active?: boolean;
}
