/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UserGetAllUserIDsRequest {
    /** Zero-based page number. If omitted, results are not paginated. */
    page?: number;
    /** Number of results per page (default is 500). */
    per_page?: number;
}
