/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UserGetInfoForUserIdRequest {
    /** user ID to query for */
    user_id?: string;
    /** reference ID to query for */
    reference_id?: string;
}
