/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Access revoked event when a user revokes access through the provider
 */
export interface AccessRevokedEvent {
    type: "access_revoked";
    /** User who revoked access */
    user: Terra.TerraUser;
    /** Status of the event */
    status: "warning";
    /** Information about the access revocation */
    message: string;
}
