/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface Activity {
    /** Number of minutes spent at various intensities during the workout, as reported by the Fitness Data provider. */
    active_durations_data?: Terra.ActiveDurationsData;
    /** Object containing calorie-related information for the user during the specific workout. */
    calories_data?: Terra.CaloriesData;
    /** Cheat detection flag. */
    cheat_detection?: number;
    /** Object containing Terra Scores. */
    data_enrichment?: Terra.DataEnrichment;
    /** Object containing information on the device which recorded the specific workout. */
    device_data?: Terra.DeviceData;
    /** Object containing information related to distance covered during the associated workout. */
    distance_data?: Terra.DistanceData;
    /** Object containing information on the energy expended by the user during the workout. */
    energy_data?: Terra.EnergyData;
    /** Object containing heartrate-related information for the workout. */
    heart_rate_data?: Terra.HeartRateData;
    /** Object containing information on data for each lap performed by the user - mostly relates to track & field running activities, and swimming activities. */
    lap_data?: Terra.LapData;
    /** Object containing information on the Metabolic Equivalent of Task for the workout. */
    MET_data?: Terra.MetData;
    /** Object containing workout metadata. */
    metadata: Terra.ActivityMetadata;
    /** Object containing information on the user's movement throughout the workout. */
    movement_data?: Terra.MovementData;
    /** Object containing information on oxygen-related metrics for the workout. */
    oxygen_data?: Terra.OxygenData;
    /** Object containing polyline-representation map data, plotting the user's trajectory throughout the workout. */
    polyline_map_data?: Terra.PolylineMapData;
    /** Object containing information on the user's position throughout the workout. */
    position_data?: Terra.PositionData;
    /** Object containing information on the power generated by the user during the workout. */
    power_data?: Terra.PowerData;
    /** Object containing information on the cardiovascular strain imposed on the user during the workout. */
    strain_data?: Terra.StrainData;
    /** Object containing information on the stress put on the user's body from a workout. */
    TSS_data?: Terra.TssData;
    /** Object containing information on the work output of the user during the workout. */
    work_data?: Terra.WorkData;
}
