/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * User is engaged in vigorous physical activity such as running or intense exercise.
 */
export type ActivityLevel = number;
