/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface ActiveDurationsData {
    /** Array of detailed samples of the intensity the user was in at various points during the workout. */
    activity_levels_samples?: Terra.ActivityLevelSample[];
    /** Total number of seconds spent in an active state during the workout. */
    activity_seconds?: number;
    /** Total number of seconds spent in an inactive state during the workout. */
    inactivity_seconds?: number;
    /** Total number of seconds spent in a low intensity state during the workout. */
    low_intensity_seconds?: number;
    /** Total number of seconds spent in a moderate intensity state during the workout. */
    moderate_intensity_seconds?: number;
    /** Maximum number of continuous periods spent in an inactive state during the workout. */
    num_continuous_inactive_periods?: number;
    /** Total number of seconds spent resting during the workout. */
    rest_seconds?: number;
    /** Total number of seconds spent in a state of vigorous intensity during the workout. */
    vigorous_intensity_seconds?: number;
    standing_hours_count?: number;
    standing_seconds?: number;
}
