/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface ActivityMetadata {
    /** The City in which the workout was performed. */
    city?: string;
    /** The Country in which the workout was performed. */
    country?: string;
    /** The end time of the associated workout, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    end_time: string;
    /** The name - either user-entered or given by the fitness data provider - of the associated workout. */
    name?: string;
    /** The start time of the associated workout, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    start_time: string;
    /** The State in which the workout was performed. */
    state?: string;
    /** A unique identifier for the workout - note that this is unique for the given user, and may not be globally unique. */
    summary_id: string;
    timestamp_localization?: Terra.TimestampLocalization;
    /** The type of activity performed for the associated workout. */
    type: Terra.Hurling;
    /** The upload type for the associated workout, providing information on whether this was an automatic workout or user-entered. */
    upload_type: Terra.UploadType;
}
