/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Activity data event
 */
export interface ActivityEvent {
    type: "activity";
    /** Array of activity data */
    data: Terra.Activity[];
    /** User whose data is being provided */
    user: Terra.TerraUser;
    /** API version */
    version: string;
}
