/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface Athlete {
    /** User's age. */
    age?: number;
    /** User's country of residence. */
    country?: string;
    /** User's bio - a short description they display on their profile. */
    bio?: string;
    /** User's state of residence. */
    state?: string;
    /** User's last name. */
    last_name?: string;
    /** User's sex. */
    sex?: string;
    /** User's city of residence. */
    city?: string;
    /** User's email. */
    email?: string;
    /** User's date of birth, in ISO8601 format. */
    date_of_birth?: string;
    /** User's first name. */
    first_name?: string;
    /** User's gender. */
    gender?: string;
    /** User's account creation date. */
    joined_provider?: string;
    devices?: Terra.DeviceData[];
}
