/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Athlete data event
 */
export interface AthleteEvent {
    type: "athlete";
    /** Athlete data */
    athlete: Terra.Athlete;
    /** User whose data is being provided */
    user: Terra.TerraUser;
    /** API version */
    version: string;
}
