/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface AthleteCollection {
    /** Object containing the user's information */
    athlete?: Terra.Athlete;
    /** Terra User object */
    user?: Terra.TerraUser;
}
