/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Authentication success event
 */
export interface AuthSuccessEvent extends Terra.AuthEvent {
    /** User who authenticated */
    user: Terra.TerraUser;
    /** Client-provided reference ID */
    reference_id: string;
    /** Widget session identifier */
    widget_session_id: string;
}
