/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AwakeDurations {
    /** Total duration for which the user was awake during the sleep session. */
    duration_awake_state_seconds?: number;
    /** Total duration for which the user was awake during the sleep session, when the interruption of their sleep was greater than 90 seconds. */
    duration_long_interruption_seconds?: number;
    /** Total duration for which the user was awake during the sleep session, when the interruption of their sleep was less than 90 seconds. */
    duration_short_interruption_seconds?: number;
    /** Number of times the user got out of bed during the sleep session. */
    num_out_of_bed_events?: number;
    /** Number of times the user woke up during the sleep session. */
    num_wakeup_events?: number;
    /** Sleep latency, defined as time between the moment the user lays in bed with the intention to sleep and the moment they actually fall asleep. */
    sleep_latency_seconds?: number;
    /** Wake up latency, defined as time between the moment the user wakes up and the moment they get out of bed. */
    wake_up_latency_seconds?: number;
}
