/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface BloodPressureData {
    /** List of Blood Pressure measurements sampled throughout the day. */
    blood_pressure_samples?: Terra.BloodPressureSample[];
}
