/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Body data event
 */
export interface BodyEvent {
    type: "body";
    /** Array of body data */
    data: Terra.Body[];
    /** User whose data is being provided */
    user: Terra.TerraUser;
    /** API version */
    version: string;
}
