/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface Body {
    /** Object containing information on user's Blood Pressure. */
    blood_pressure_data?: Terra.BloodPressureData;
    /** Object containing information on the device which recorded data for the payload. */
    device_data?: Terra.DeviceData;
    /** Object containing information on user's heart metrics. */
    heart_data?: Terra.HeartData;
    /** Object containing information on user's hydration (both internal & consumption of water) for the day. */
    hydration_data?: Terra.HydrationData;
    /** Object containing information on user's ketone data for the day. */
    ketone_data?: Terra.KetoneData;
    /** Object containing information on body measurements for the day. */
    measurements_data?: Terra.MeasurementsData;
    /** Object containing daily summary metadata. */
    metadata: Terra.BodyMetadata;
    /** Object containing information on user's oxygen-related data. */
    oxygen_data?: Terra.OxygenData;
    /** Object containing temperature information (core, skin, ambient) during the day. */
    temperature_data?: Terra.TemperatureData;
    /** Object containing information on user's blood glucose for the day. */
    glucose_data?: Terra.GlucoseData;
}
