/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface BreathsData {
    /** Average breathing rate of the user during the sleep session. */
    avg_breaths_per_min?: number;
    /** Maximum breathing rate of the user during the sleep session. */
    max_breaths_per_min?: number;
    /** Minimum breathing rate of the user during the sleep session. */
    min_breaths_per_min?: number;
    /** Flag indicating if the reading was performed on demand, or if it was automatically captured by the device. */
    on_demand_reading?: boolean;
    /** List of breathing rate information sampled throughout the sleep session. */
    samples?: Terra.BreathSample[];
    /** The start time of the recording of breathing rate data, in ISO8601 format with microsecond precision. Will always fall on midnight of any given day, and will always be equal to 24h before end_time. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    start_time?: string;
    /** The end time of the recording of breathing rate data, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    end_time?: string;
}
