/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface CaloriesData {
    BMR_calories?: number;
    calorie_samples?: Terra.CalorieSample[];
    net_activity_calories?: number;
    net_intake_calories?: number;
    total_burned_calories?: number;
}
