/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Connection error event
 */
export interface ConnectionErrorEvent {
    type: "connection_error";
    /** User with connection issues */
    user: Terra.TerraUser;
    /** Status of the event */
    status: "warning";
    /** Information about the connection issue */
    message: string;
}
