/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DailyPatternSample {
    time_from_midnight: number;
    percentile_5: number;
    percentile_25: number;
    percentile_50: number;
    percentile_75: number;
    percentile_95: number;
}
