/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface Daily {
    /** Object containing information related to the time spent in different activity intensities during over the day. */
    active_durations_data?: Terra.ActiveDurationsData;
    /** Object containing calorie-related information for the user during the specific day. */
    calories_data?: Terra.CaloriesData;
    /** Object containing additional enrichment data for the day. */
    data_enrichment?: Terra.DailyDataEnrichment;
    /** Object containing information on the device which recorded data for the day. */
    device_data?: Terra.DeviceData;
    /** Object containing information related to distance covered during the associated day. */
    distance_data?: Terra.DailyDistanceData;
    /** Object containing heartrate-related information for the day. */
    heart_rate_data?: Terra.HeartRateData;
    /** Object containing information on the Metabolic Equivalent of Task for the day. */
    MET_data?: Terra.MetData;
    /** Object containing daily summary metadata. */
    metadata: Terra.DailyMetadata;
    /** Object containing information on oxygen-related metrics for the day. */
    oxygen_data?: Terra.OxygenData;
    /** Scores for the user's performance on different metrics for the given day, as calculated by the fitness data provider. */
    scores?: Terra.ScoresData;
    /** Object containing information on the strain put on the user's body over a day. */
    strain_data?: Terra.StrainData;
    /** Object containing information on the stress put on the user over a day. */
    stress_data?: Terra.StressData;
    /** Object containing all user-entered or automatically tagged events in the day. */
    tag_data?: Terra.TagData;
}
