/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Daily data event
 */
export interface DailyEvent {
    type: "daily";
    /** Array of daily data */
    data: Terra.Daily[];
    /** User whose data is being provided */
    user: Terra.TerraUser;
    /** API version */
    version: string;
}
