/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface DailyDataEnrichment {
    cardiovascular_contributors?: Terra.DataContributor[];
    cardiovascular_score?: number;
    immune_contributors?: Terra.DataContributor[];
    immune_index?: number;
    readiness_contributors?: Terra.DataContributor[];
    readiness_score?: number;
    respiratory_contributors?: Terra.DataContributor[];
    respiratory_score?: number;
    start_time?: string;
    stress_contributors?: Terra.DataContributor[];
    total_stress_score?: number;
}
