/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface DailyDistanceData {
    /** Object containing detailed distance information - this may include second-by-second samples. */
    detailed?: Terra.DistanceDataDetailed;
    /** Total distance covered by the user throughout the day. */
    distance_meters?: number;
    /** Average elevation of the user throughout the day. */
    elevation?: Terra.ElevationData;
    /** Total number of elevation gain in floors climbed equivalent throughout the day, as determined by the fitness data provider. */
    floors_climbed?: number;
    /** Total number of steps performed during the day. */
    steps?: number;
    /** Summary information of the user's swimming statistics for the day, if applicable. */
    swimming?: Terra.SwimmingData;
}
