/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface DataSentToWebhook {
    /** Payload reference, tying the request to the webhook payload which will be received */
    reference?: string;
    message?: string;
    /** Terra User object */
    user?: Terra.TerraUser;
}
