/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * User deauthentication event
 */
export interface DeauthEvent {
    type: "deauth";
    /** User who deauthenticated */
    user: Terra.TerraUser;
    /** Status of deauthentication */
    status: "success";
    /** Confirmation message */
    message: string;
}
