/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface DeviceData {
    /** Activation timestamp of the device, if applicable. */
    activation_timestamp?: string;
    /** Data provided by the device, as enumerated types. */
    data_provided?: Terra.DeviceDataType[];
    /** Hardware version of the device. */
    hardware_version?: string;
    /** Last upload date from the device. */
    last_upload_date?: string;
    /** Device manufacturer name. */
    manufacturer?: string;
    /** Device name - note that this can also be the name of the application/package which the data comes from, if coming from a data aggregator such as Google Fit. */
    name?: string;
    /** Data pertaining to other devices which may have contributed data for this workout. */
    other_devices?: Terra.OtherDeviceData[];
    /** Sensor state of the device. */
    sensor_state?: string;
    /** Device Serial Number. */
    serial_number?: string;
    /** Device Software Version. */
    software_version?: string;
}
