/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Represents data types that a certain device contributed to.
 */
export type DeviceDataType =
    /**
     * Count of steps taken by the user. */
    | "STEPS"
    /**
     * Duration of time the user spent in physical activity. */
    | "ACTIVE_MINUTES"
    /**
     * User's basal metabolic rate - calories burned at rest. */
    | "BMR"
    /**
     * Calories burned by the user during activity. */
    | "CALORIES"
    /**
     * Distance traveled by the user during activity. */
    | "DISTANCE"
    /**
     * User's heart rate measurements. */
    | "HEART_RATE"
    /**
     * Blood oxygen saturation level (SpO2) of the user. */
    | "OXYGEN_SATURATION"
    /**
     * Classification of user's sleep stages or types. */
    | "SLEEP_TYPE"
    /**
     * User's movement speed during activity. */
    | "SPEED"
    /**
     * Rate of movement repetition during activity (steps per minute). */
    | "CADENCE";
export const DeviceDataType = {
    Steps: "STEPS",
    ActiveMinutes: "ACTIVE_MINUTES",
    Bmr: "BMR",
    Calories: "CALORIES",
    Distance: "DISTANCE",
    HeartRate: "HEART_RATE",
    OxygenSaturation: "OXYGEN_SATURATION",
    SleepType: "SLEEP_TYPE",
    Speed: "SPEED",
    Cadence: "CADENCE",
} as const;
