/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface DistanceDataSummary {
    /** Total distance covered by the user throughout the workout. */
    distance_meters?: number;
    /** Average elevation of the user throughout the workout. */
    elevation?: Terra.ElevationData;
    /** Total number of elevation gain in floors climbed equivalent throughout the workout, as determined by the fitness data provider. */
    floors_climbed?: number;
    /** Total number of steps performed during the workout. */
    steps?: number;
    /** Summary information of the user's swimming statistics for the workout, if applicable. */
    swimming?: Terra.SwimmingData;
}
