/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface DistanceDataDetailed {
    /** Array of detailed samples of distance covered throughout the workout. */
    distance_samples?: Terra.DistanceSample[];
    /** Array of detailed samples of elevation throughout the workout. */
    elevation_samples?: Terra.ElevationSample[];
    /** Array of detailed samples of floors climbed throughout the workout, as determined by the fitness data provider. */
    floors_climbed_samples?: Terra.FloorsClimbedSample[];
    /** Array of detailed samples of steps performed throughout the workout. */
    step_samples?: Terra.StepSample[];
}
