/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface DistanceData {
    /** Object containing detailed distance information - this may included second-by-second samples. */
    detailed?: Terra.DistanceDataDetailed;
    /** Object containing summary information related to distance covered throughout the workout. */
    summary?: Terra.DistanceDataSummary;
}
