/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DrinkSample {
    timestamp: string;
    drink_volume: number;
    drink_unit: string;
    drink_name: string;
}
