/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface EcgReading {
    start_timestamp: string;
    avg_hr_bpm: number;
    afib_classification: Terra.Inconclusive;
    raw_signal: Terra.RawEcgSample[];
}
