/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ElevationData {
    /** Average elevation of the user throughout the workout. */
    avg_meters?: number;
    /** Planned elevation gain for the workout. */
    gain_actual_meters?: number;
    /** Elevation gain of the user throughout the workout - this includes all elevation gain, and does _not_ represent net gain. */
    gain_planned_meters?: number;
    /** Elevation loss of the user throughout the workout. */
    loss_actual_meters?: number;
    /** Maximum elevation of the user during the workout. */
    max_meters?: number;
    /** Minimum elevation of the user during the workout. */
    min_meters?: number;
}
