/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EnergyData {
    /** Total number of kiloJoules planned to be expended during the workout - represents the user's predefined goal for the workout */
    energy_kilojoules?: number;
    /** Total number of kiloJoules expended during the workout */
    energy_planned_kilojoules?: number;
}
