/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FloorsClimbedSample {
    /** Time with which the record is associated, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    timestamp?: string;
    /** Cumulative number of elevation gain measured in floors climbed up to associated timestamp, since the start of the payload */
    floors_climbed?: number;
    /** Time elapsed since the start of the workout, subtracting time during which the recording was paused */
    timer_duration_seconds?: number;
}
