/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FloorsClimbedSample {
    timestamp: string;
    floors_climbed: number;
    timer_duration_seconds: number;
}
