/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface GlucoseData {
    /** List of blood glucose readings sampled throughout the day. */
    blood_glucose_samples?: Terra.GlucoseDataSample[];
    /** List of blood glucose readings sampled throughout the day - this represents additional data points, potentially at higher frequency from the ones in blood_glucose_samples, which may come at a cost of reduced accuracy. */
    detailed_blood_glucose_samples?: Terra.GlucoseDataSample[];
    /** User's average glucose level throughout the day. */
    day_avg_blood_glucose_mg_per_dL?: number;
    /** GMI (Glucose Management Indicator) is a metric derived from continuous glucose monitoring (CGM) data that estimates average glucose levels to help guide diabetes management, without implying a precise match to laboratory A1C. */
    gmi?: number;
    /** Time that the user's glucose is within acceptable range (not hyper or hypoglycemic). */
    time_in_range?: number;
    /** Number of data points recorded by the sensor throughout the day. */
    sensor_usage?: number;
    /** List of glucose percentile samples throughout the day. */
    daily_patterns?: Terra.DailyPatternSample[];
}
