/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GlucoseDataSample {
    timestamp: string;
    blood_glucose_mg_per_dL: number;
    glucose_level_flag: number;
    trend_arrow: number;
}
