/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface GlucoseDataSample {
    /** Time with which the record is associated, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    timestamp?: string;
    /** User's blood glucose reading */
    blood_glucose_mg_per_dL?: number;
    /** Flag indicating state of user's blood glucose level */
    glucose_level_flag?: Terra.Low;
    /** Flag indicating the current trend in the user's blood glucose level (e.g. rising, constant, falling) */
    trend_arrow?: Terra.TrendArrow;
}
