/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Google no datasource event
 */
export interface GoogleNoDatasourceEvent {
    type: "google_no_datasource";
    /** Affected user */
    user: Terra.TerraUser;
    /** Status of the event */
    status: "warning";
    /** Information about the issue */
    message: string;
}
