/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Healthcheck event sent periodically to verify your webhook endpoint is functional
 */
export interface HealthcheckEvent {
    type: "healthcheck";
    /** Timestamp when the event was created */
    creation_timestamp: string;
    /** Percentage change in trends */
    trend_percentage: number;
    /** Number of webhooks sent in the last hour */
    sent_webhooks_last_hour: number;
}
