/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface HeartRateDataDetailed {
    /** Array of HeartRate data samples recorded for the user during the workout. */
    hr_samples?: Terra.HeartRateDataSample[];
    /** Array of HeartRate Variability data samples recorded for the user during the workout, computed using RMSSD. */
    hrv_samples_rmssd?: Terra.HeartRateVariabilityDataSampleRmssd[];
    /** Array of HeartRate Variability data samples recorded for the user during the workout, computed using SDNN. */
    hrv_samples_sdnn?: Terra.HeartRateVariabilityDataSampleSdnn[];
}
