/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface HeartRateDataSample {
    timestamp: string;
    bpm: number;
    timer_duration_seconds: number;
    context: Terra.HeartRateContext;
}
