/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface HeartRateDataSummary {
    /** Average HeartRate of the user during the workout. */
    avg_hr_bpm?: number;
    /** Average HeartRate Variability of the user during the workout, computed using RMSSD. */
    avg_hrv_rmssd?: number;
    /** Average HeartRate Variability of the user during the workout, computed using SDNN. */
    avg_hrv_sdnn?: number;
    /** Array of time spent in various HR zones throughout the workout. */
    hr_zone_data?: Terra.HeartRateZoneData[];
    /** Maximum HeartRate of the user during the workout. */
    max_hr_bpm?: number;
    /** Minimum HeartRate of the user during the workout. */
    min_hr_bpm?: number;
    /** Resting HeartRate of the user, as determined by the fitness data provider. */
    resting_hr_bpm?: number;
    /** User's maximum HeartRate based on their age, and other factors as determined by the fitness data provider. */
    user_max_hr_bpm?: number;
}
