/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface HeartRateData {
    /** Object containing detailed heart rate information for the associated workout. */
    detailed?: Terra.HeartRateDataDetailed;
    /** Object containing summary heart rate information for the associated workout. */
    summary?: Terra.HeartRateDataSummary;
}
