/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface HeartRateZoneData {
    zone: Terra.Other;
    start_percentage: number;
    end_percentage: number;
    name: string;
    duration_seconds: number;
}
