/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface HeartRateVariabilityDataSampleSdnn {
    /** Time with which the record is associated, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    timestamp?: string;
    /** User's Heart Rate Variability, computed using SDNN */
    hrv_sdnn?: number;
}
