/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface HeartRateZoneData {
    /** Heart rate zone designation */
    zone?: Terra.Other;
    /** Start percentage (based off user's max HR) of the HR zone */
    start_percentage?: number;
    /** End percentage (based off user's max HR) of the HR zone */
    end_percentage?: number;
    /** Name of the associated heart rate zone */
    name?: string;
    /** Duration spent in the heart rate zone */
    duration_seconds?: number;
}
