/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface HydrationData {
    /** User's total water consumption throughout the day. */
    day_total_water_consumption_ml?: number;
    /** User's hydration level samples throughout the day. */
    hydration_amount_samples?: Terra.HydrationMeasurementSample[];
}
