/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The heart rhythm analysis couldn't determine whether AFib was present or absent.
 */
export type Inconclusive = number;
