/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IntegrationProvider {
    /** Identifier for the provider */
    provider?: string;
    /** Display name of the integration */
    name?: string;
    /** URL for the provider's icon image */
    icon?: string;
    /** Indicates how the integration is set up */
    setup?: string;
    /** Whether the integration is enabled */
    enabled?: boolean;
    /** Indicates the types of data available through the provider */
    types?: IntegrationProvider.Types;
}

export namespace IntegrationProvider {
    /**
     * Indicates the types of data available through the provider
     */
    export interface Types {
        activity?: boolean;
        body?: boolean;
        nutrition?: boolean;
        daily?: boolean;
        sleep?: boolean;
        menstruation?: boolean;
    }
}
