/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface IntegrationsResponse {
    /** Status of the API response */
    status?: string;
    /** List of integration providers with their details */
    providers?: Terra.IntegrationProvider[];
}
