/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface KetoneData {
    /** List of ketone data sampled through the day. */
    ketone_samples?: Terra.KetoneSample[];
}
