/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface KetoneSample {
    timestamp: string;
    ketone_mg_per_dL: number;
    sample_type: Terra.Breath;
}
