/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface LapData {
    /** Array of datapoints for each lap performed by the user during the workout. */
    laps?: Terra.LapSample[];
}
