/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface LapSample {
    start_time: string;
    end_time: string;
    distance_meters: number;
    calories: number;
    total_strokes: number;
    stroke_type: Terra.StrokeType;
    avg_speed_meters_per_second: number;
}
