/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Large request sending event
 */
export interface LargeRequestSendingEvent {
    type: "large_request_sending";
    /** User whose data is being sent */
    user: Terra.TerraUser;
    /** Reference ID for tracking this request */
    reference: string;
    /** Information about the request */
    message: string;
    /** Number of expected payload events */
    expected_payloads: number;
}
