/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Large request processing event
 */
export interface LargeRequestProcessingEvent {
    type: "large_request_processing";
    /** Status of the processing */
    status: "processing";
    /** Information about the processing */
    message: string;
    /** User whose data is being processed */
    user: Terra.TerraUser;
    /** Reference ID for tracking this request */
    reference: string;
}
