/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface Meal {
    /** Micronutrient information for associated food. */
    micros: Terra.NutritionMicros;
    /** Enum representing the category the consumed food/meal falls under (i.e. Breakfast/Lunch/Dinner etc). */
    type: Terra.Snack;
    /** Identifier for food logged by the user. */
    id: string;
    /** Timestamp the food is associated with, in ISO8601 format, with microsecond precision. */
    timestamp: string;
    /** Quantity of the food that was consumed, containing information on amount & units in which this was recorded. */
    quantity: Terra.NutritionQuantity;
    /** Name of food logged by the user. */
    name: string;
    /** Macronutrient information for associated food. */
    macros: Terra.NutritionMacros;
}
