/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MeasurementDataSample {
    /** Time with which the record is associated, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    measurement_time?: string;
    /** User's Body Mass Index (BMI). */
    BMI?: number;
    /** User's Basal Metabolic Rate - minimum amount of calories that a person's body needs to perform necessary functions. */
    BMR?: number;
    /** User's Resting Metabolic Rate - amount of energy that a person's body needs to function while at rest. RMR accounts for additional low-effort daily activities on top of basic body functions. */
    RMR?: number;
    /** Estimate of how fit the user is compared to their actual age, as measured by the device. */
    estimated_fitness_age?: string;
    /** User's skin fold measurement. */
    skin_fold_mm?: number;
    /** User's body fat percentage. */
    bodyfat_percentage?: number;
    /** User's body weight. */
    weight_kg?: number;
    /** User's height. */
    height_cm?: number;
    /** User's total bone mass. */
    bone_mass_g?: number;
    /** User's total muscle mass (i.e. skeletal muscle mass). */
    muscle_mass_g?: number;
    /** Total lean mass of the user - calculated as the difference between total body weight and body fat weight. */
    lean_mass_g?: number;
    /** Total amount of fluid in the user's body. */
    water_percentage?: number;
    /** Quantity of insulin administered to the user. */
    insulin_units?: number;
    /** Type of insulin administered to the user. */
    insulin_type?: string;
    /** Color of the user's urine. */
    urine_color?: string;
    /** User notes associated with the measurement. */
    user_notes?: string;
}
