/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface MeasurementsData {
    /** List of body metrics & measurements taken throughout the associated day. */
    measurements?: Terra.MeasurementDataSample[];
}
