/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface Menstruation {
    /** Object containing daily summary metadata. */
    metadata: Terra.MenstruationMetadata;
    /** Object containing information on user's menstruation for a given day. */
    menstruation_data?: Terra.MenstruationData;
}
