/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Menstruation data event
 */
export interface MenstruationEvent {
    type: "menstruation";
    /** Array of menstruation data */
    data: Terra.Menstruation[];
    /** User whose data is being provided */
    user: Terra.TerraUser;
    /** API version */
    version: string;
}
