/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface MenstruationData {
    /** Total length of period (i.e. menstrual bleeding). */
    period_length_days?: number;
    /** Phase in associated cycle, (i.e. menstruation, fertile etc). */
    current_phase?: Terra.MenstrualPhase;
    /** Length of current phase. */
    length_of_current_phase_days?: number;
    /** Number of days to reach the next phase (predicted). */
    days_until_next_phase?: number;
    /** Start date of menstrual cycle, in ISO8601 format. */
    period_start_date?: string;
    /** Prediction of the cycle's total length. */
    predicted_cycle_length_days?: number;
    /** Number of day in cycle this object is associated with. */
    day_in_cycle?: number;
    /** Last time when the user recorded information regarding their cycle, in ISO8601 format, with microseconds precision. */
    last_updated_time?: string;
    /** Total cycle length. */
    cycle_length_days?: string;
    /** Flag indicating whether associated object is a prediction or user-logged information. */
    is_predicted_cycle?: string;
    /** List of user logs of information related to the strength of user's menstrual flow. */
    menstruation_flow?: Terra.MenstruationFlowSample[];
}
