/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Represents menstrual cycle phases.
 */
export type MenstrualPhase =
    /**
     * The menstrual phase when bleeding occurs. */
    | "menstrual"
    /**
     * The follicular phase when follicles in ovaries develop. */
    | "follicular"
    /**
     * The ovulation phase when an egg is released. */
    | "ovulation"
    /**
     * The luteal phase following ovulation. */
    | "luteal"
    /**
     * Premenstrual syndrome phase before menstruation begins. */
    | "pms"
    /**
     * The fertile window when conception is most likely. */
    | "fertile"
    /**
     * First third of pregnancy, weeks 1-12. */
    | "first_trimester"
    /**
     * Middle third of pregnancy, weeks 13-26. */
    | "second_trimester"
    /**
     * Final third of pregnancy, weeks 27-40. */
    | "third_trimester"
    /**
     * Menstrual cycle phase could not be determined. */
    | "unknown";
export const MenstrualPhase = {
    Menstrual: "menstrual",
    Follicular: "follicular",
    Ovulation: "ovulation",
    Luteal: "luteal",
    Pms: "pms",
    Fertile: "fertile",
    FirstTrimester: "first_trimester",
    SecondTrimester: "second_trimester",
    ThirdTrimester: "third_trimester",
    Unknown: "unknown",
} as const;
