/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface MetData {
    /** An array of Metabolic Equivalent Time samples, as calculated by the user's wearable. */
    MET_samples?: Terra.MetSample[];
    /** The average MET level of the activity. */
    avg_level?: number;
    /** Number of minutes spent in High Intensity during the workout - based off MET scale. */
    num_high_intensity_minutes?: number;
    /** Number of minutes spent in state of Inactivity during the workout - based off MET scale. */
    num_inactive_minutes?: number;
    /** Number of minutes spent in Low Intensity during the workout - based off MET scale. */
    num_low_intensity_minutes?: number;
    /** Number of minutes spent in Moderate Intensity during the workout - based off MET scale. */
    num_moderate_intensity_minutes?: number;
}
