/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface MovementData {
    /** Adjusted max speed of the user during the workout - generated using Terra's algorithms to remove potential affecting the user's actual max speed measurement. */
    adjusted_max_speed_meters_per_second?: number;
    /** Average cadence of the user during the workout, in RPM. */
    avg_cadence_rpm?: number;
    /** Average pace of the user during the workout. */
    avg_pace_minutes_per_kilometer?: number;
    /** Average speed of the user during the workout. */
    avg_speed_meters_per_second?: number;
    /** Average torque generated by the user during the workout - mainly relevant for cycling activities. */
    avg_torque_newton_meters?: number;
    /** Average velocity of the user during the workout - only calculated by certain providers, representing a separate quantity from speed. */
    avg_velocity_meters_per_second?: number;
    /** Array of cadence values recorded throughout the workout, sampled at intervals determined by the fitness data provider. */
    cadence_samples?: Terra.CadenceSample[];
    /** Maximum cadence of the user during the workout - mainly relevant for cycling activities. */
    max_cadence_rpm?: number;
    /** Maximum pace of the user during the workout. */
    max_pace_minutes_per_kilometer?: number;
    /** Maximum speed of the user during the workout. */
    max_speed_meters_per_second?: number;
    /** Maximum torque generated by the user during the workout - mainly relevant for cycling activities. */
    max_torque_newton_meters?: number;
    /** Maximum velocity of the user during the workout - only calculated by certain providers, representing a separate quantity from speed. */
    max_velocity_meters_per_second?: number;
    /** Average normalized speed of the user during the workout - only calculated by certain providers, representing a separate quantity from speed. */
    normalized_speed_meters_per_second?: number;
    /** Array of the datapoints for the user's speed sampled throughout the workout. */
    speed_samples?: Terra.SpeedSample[];
    /** Array of the datapoints for the user's torque sampled throughout the workout. */
    torque_samples?: Terra.TorqueSample[];
}
