/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface NoDataReturned {
    status?: NoDataReturned.Status;
    message?: string;
    /** Terra User object */
    user?: Terra.TerraUser;
}

export namespace NoDataReturned {
    export type Status = "success" | "error";
    export const Status = {
        Success: "success",
        Error: "error",
    } as const;
}
