/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface NotFoundErrorBody {
    /** a detailed message describing the error */
    message?: string;
    /** indicates that an error happened (value is error) */
    status?: "error";
}
