/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface NutritionQuantity {
    unit: Terra.NutritionUnits;
    amount: number;
}
