/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface Nutrition {
    /** Information on drinks the user consumed throughout the day. */
    drink_samples?: Terra.DrinkSample[];
    /** Information on individual foods consumed throughout a given day. */
    meals?: Terra.Meal[];
    /** Object containing daily summary metadata. */
    metadata: Terra.NutritionMetadata;
    /** Summative nutritional information for a given day. */
    summary?: Terra.NutritionSummary;
}
