/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface NutritionMicros {
    /** Biotin content of the associated food(s). */
    biotin_mg?: number;
    /** Caffeine content of the associated food(s). */
    caffeine_mg?: number;
    /** Calcium content of the associated food(s). */
    calcium_mg?: number;
    /** Chloride content of the associated food(s). */
    chloride_mg?: number;
    /** Chromium content of the associated food(s). */
    chromium_mg?: number;
    /** Copper content of the associated food(s). */
    copper_mg?: number;
    /** Folate content of the associated food(s). */
    folate_mg?: number;
    /** Folic Acid content of the associated food(s). */
    folic_acid_mg?: number;
    /** Iodine content of the associated food(s). */
    iodine_mg?: number;
    /** Iron content of the associated food(s). */
    iron_mg?: number;
    /** Magnesium content of the associated food(s). */
    magnesium_mg?: number;
    /** Manganese content of the associated food(s). */
    manganese_mg?: number;
    /** Molybdenum content of the associated food(s). */
    molybdenum_mg?: number;
    /** Niacin content of the associated food(s). */
    niacin_mg?: number;
    /** Pantothenic content of the associated food(s). */
    pantothenic_acid_mg?: number;
    /** Phosphorus content of the associated food(s). */
    phosphorus_mg?: number;
    /** Potassium content of the associated food(s). */
    potassium_mg?: number;
    /** Riboflavin content of the associated food(s). */
    riboflavin_mg?: number;
    /** Selenium content of the associated food(s). */
    selenium_mg?: number;
    /** Thiamin content of the associated food(s). */
    thiamin_mg?: number;
    /** Vitamin A content of the associated food(s). */
    vitamin_A_mg?: number;
    /** Vitamin B12 content of the associated food(s). */
    vitamin_B12_mg?: number;
    /** Vitamin B6 content of the associated food(s). */
    vitamin_B6_mg?: number;
    /** Vitamin C content of the associated food(s). */
    vitamin_C_mg?: number;
    /** Vitamin D content of the associated food(s). */
    vitamin_D_mg?: number;
    /** Vitamin D2 content of the associated food(s). */
    vitamin_D2_mg?: number;
    /** Vitamin D3 content of the associated food(s). */
    vitamin_D3_mg?: number;
    /** Vitamin E content of the associated food(s). */
    vitamin_E_mg?: number;
    /** Vitamin K content of the associated food(s). */
    vitamin_K_mg?: number;
    /** Zinc content of the associated food(s). */
    zinc_mg?: number;
    /** Cystine content of the associated food(s). */
    cystine_g?: number;
    /** Histidine content of the associated food(s). */
    histidine_g?: number;
    /** Isoleucine content of the associated food(s). */
    isoleucine_g?: number;
    /** Leucine content of the associated food(s). */
    leucine_g?: number;
    /** Lysine content of the associated food(s). */
    lysine_g?: number;
    /** Methionine content of the associated food(s). */
    methionine_g?: number;
    /** Phenylalanine content of the associated food(s). */
    phenylalanine_g?: number;
    /** Threonine content of the associated food(s). */
    threonine_g?: number;
    /** Tryptophan content of the associated food(s). */
    tryptophan_g?: number;
    /** Tyrosine content of the associated food(s). */
    tyrosine_g?: number;
    /** Valine content of the associated food(s). */
    valine_g?: number;
    /** Monounsaturated fat content of the associated food(s). */
    monounsaturated_fat_g?: number;
    /** Polyunsaturated fat content of the associated food(s). */
    polyunsaturated_fat_g?: number;
    /** Omega3 content of the associated food(s). */
    omega3_g?: number;
    /** Omega6 content of the associated food(s). */
    omega6_g?: number;
    /** Starch content of the associated food(s). */
    starch_g?: number;
}
