/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface NutritionMacros {
    /** Alcohol content of the associated food(s). */
    alcohol_g?: number;
    /** Calorie content of the associated food(s). */
    calories?: number;
    /** Carbohydrates content of the associated food(s). */
    carbohydrates_g?: number;
    /** Cholesterol content of the associated food(s). */
    cholesterol_mg?: number;
    /** Fat content of the associated food(s). */
    fat_g?: number;
    /** Fiber content of the associated food(s). */
    fiber_g?: number;
    /** Net carbs content of the associated food(s). */
    net_carbohydrates_g?: number;
    /** Protein content of the associated food(s). */
    protein_g?: number;
    /** Saturated fat content of the associated food(s). */
    saturated_fat_g?: number;
    /** Sodium content of the associated food(s). */
    sodium_mg?: number;
    /** Sugar content of the associated food(s). */
    sugar_g?: number;
    /** Trans fat content of the associated food(s). */
    trans_fat_g?: number;
}
