/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OtherSleepDurations {
    /** Total duration of time spent in bed. */
    duration_in_bed_seconds?: number;
    /** Total duration during which the user's state (awake, asleep, REM, etc) was unmeasurable during the sleep session. */
    duration_unmeasurable_sleep_seconds?: number;
}
