/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface OxygenSaturationSample {
    /** Time with which the record is associated, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    timestamp?: string;
    /** User's oxygen saturation percentage - referring to either SpO2 or SmO2, based on the `type` field */
    percentage?: number;
    /** Type of oxygen saturation measurement (i.e. blood vs muscle) */
    type?: Terra.Muscle;
}
