/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface OxygenData {
    /** Average Oxygen Saturation percentage of the user during the day (SpO2 or SmO2). */
    avg_saturation_percentage?: number;
    /** Array of Oxygen Saturation percentage datapoints sampled throughout the day. */
    saturation_samples?: Terra.OxygenSaturationSample[];
    /** Array of VO2 datapoints sampled throughout the day. */
    vo2_samples?: Terra.Vo2MaxSample[];
    /** VO2Max for the given user. */
    vo2max_ml_per_min_per_kg?: number;
}
