/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface OxygenSaturationData {
    /** Average Oxygen Saturation percentage of the user during the sleep session. */
    avg_saturation_percentage?: number;
    /** The end time of the recording of oxygen saturation, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    end_time?: string;
    /** Array of Oxygen Saturation percentage datapoints sampled throughout the sleep session. */
    samples?: Terra.OxygenSaturationSample[];
    /** The start time of the recording of oxygen saturation, in ISO8601 format with microsecond precision. Will always fall on midnight of any given day, and will always be equal to 24h before end_time. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    start_time?: string;
}
