/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Permission change event
 */
export interface PermissionChangeEvent {
    type: "permission_change";
    /** User who changed permissions */
    user: Terra.TerraUser;
    /** Status of the event */
    status: "warning";
    /** Information about the permission change */
    message: string;
    /** API version */
    version: string;
    /** Newly added scopes */
    scopes_added: string;
    /** Removed scopes */
    scopes_removed: string;
}
