/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface PlannedWorkout {
    /** List of exercises/steps/intervals for the workout plan */
    steps?: Terra.PlannedWorkoutSteps[];
    /** Metadata for the workout plan */
    metadata?: Terra.PlannedWorkoutMetadata;
}
