/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PlannedWorkoutMetadata {
    /** Estimated energy expenditure for the workout */
    estimated_energy_kj?: number;
    /** Estimated speed for the workout */
    estimated_speed_meters_per_second?: number;
    /** Estimated elevation gain for the workout */
    estimated_elevation_gain_meters?: number;
    /** Estimated Training Stress Score for the workout */
    estimated_tss?: number;
    /** Estimated calorie burn for the workout */
    estimated_calories?: number;
    /** The creation datetime of the associated workout, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time */
    created_date?: string;
    /** The planned start datetime, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time */
    planned_date?: string;
    /** The name - either user-entered or given by the fitness data provider - of the associated workout plan */
    type?: PlannedWorkoutMetadata.Type;
    id?: string;
    /** Estimated workout duration */
    estimated_duration_seconds?: number;
    /** Estimated pace for the workout */
    estimated_pace_minutes_per_kilometer?: number;
    /** Name of the original source of the workout plan */
    provider?: string;
    /** */
    estimated_tscore?: number;
    /** Description of the workout */
    description?: string;
    /** Name of the workout plan */
    name?: string;
    /** Estimated distance for the workout */
    estimated_distance_meters?: number;
    /** Estimated Intensity Factor for the workout */
    estimated_if?: number;
    /** Pool length of the pool used for the workout - only relevant for swimming activity types */
    pool_length_meters?: number;
}

export namespace PlannedWorkoutMetadata {
    /**
     * The name - either user-entered or given by the fitness data provider - of the associated workout plan
     */
    export type Type =
        | "IN_VEHICLE"
        | "BIKING"
        | "STILL"
        | "UNKNOWN"
        | "TILTING"
        | "WALKING"
        | "RUNNING"
        | "AEROBICS"
        | "BADMINTON"
        | "BASEBALL"
        | "BASKETBALL"
        | "BIATHLON"
        | "HANDBIKING"
        | "MOUNTAIN_BIKING"
        | "ROAD_BIKING"
        | "SPINNING"
        | "STATIONARY_BIKING"
        | "UTILITY_BIKING"
        | "BOXING"
        | "CALISTHENICS"
        | "CIRCUIT_TRAINING"
        | "CRICKET"
        | "DANCING"
        | "ELLIPTICAL"
        | "FENCING"
        | "AMERICAN_FOOTBALL"
        | "AUSTRALIAN_FOOTBALL"
        | "ENGLISH_FOOTBALL"
        | "FRISBEE"
        | "GARDENING"
        | "GOLF"
        | "GYMNASTICS"
        | "HANDBALL"
        | "HIKING"
        | "HOCKEY"
        | "HORSEBACK_RIDING"
        | "HOUSEWORK"
        | "JUMPING_ROPE"
        | "KAYAKING"
        | "KETTLEBELL_TRAINING"
        | "KICKBOXING"
        | "KITESURFING"
        | "MARTIAL_ARTS"
        | "MEDITATION"
        | "MIXED_MARTIAL_ARTS"
        | "P90X_EXERCISES"
        | "PARAGLIDING"
        | "PILATES"
        | "POLO"
        | "RACQUETBALL"
        | "ROCK_CLIMBING"
        | "ROWING"
        | "ROWING_MACHINE"
        | "RUGBY"
        | "JOGGING"
        | "RUNNING_ON_SAND"
        | "TREADMILL_RUNNING"
        | "SAILING"
        | "SCUBA_DIVING"
        | "SKATEBOARDING"
        | "SKATING"
        | "CROSS_SKATING"
        | "INDOOR_ROLLERBLADING"
        | "SKIING"
        | "BACK_COUNTRY_SKIING"
        | "CROSS_COUNTRY_SKIING"
        | "DOWNHILL_SKIING"
        | "KITE_SKIING"
        | "ROLLER_SKIING"
        | "SLEDDING"
        | "SNOWBOARDING"
        | "SNOWMOBILE"
        | "SNOWSHOEING"
        | "SQUASH"
        | "STAIR_CLIMBING"
        | "STAIR_CLIMBING_MACHINE"
        | "STAND_UP_PADDLEBOARDING"
        | "STRENGTH_TRAINING"
        | "SURFING"
        | "SWIMMING"
        | "SWIMMING_SWIMMING_POOL"
        | "SWIMMING_OPEN_WATER"
        | "TABLE_TENNIS"
        | "TEAM_SPORTS"
        | "TENNIS"
        | "TREADMILL"
        | "VOLLEYBALL"
        | "VOLLEYBALL_BEACH"
        | "VOLLEYBALL_INDOOR"
        | "WAKEBOARDING"
        | "WALKING_FITNESS"
        | "NORDIC_WALKING"
        | "WALKING_TREADMILL"
        | "WATERPOLO"
        | "WEIGHTLIFTING"
        | "WHEELCHAIR"
        | "WINDSURFING"
        | "YOGA"
        | "ZUMBA"
        | "DIVING"
        | "ERGOMETER"
        | "ICE_SKATING"
        | "INDOOR_SKATING"
        | "CURLING"
        | "OTHER"
        | "CROSSFIT"
        | "HIIT"
        | "INTERVAL_TRAINING"
        | "WALKING_STROLLER"
        | "ELEVATOR"
        | "ESCALATOR"
        | "ARCHERY"
        | "SOFTBALL"
        | "GUIDED_BREATHING"
        | "CARDIO_TRAINING"
        | "LACROSSE"
        | "STRETCHING"
        | "TRIATHLON"
        | "INLINE_SKATING"
        | "SKY_DIVING"
        | "PADDLING"
        | "MOUNTAINEERING"
        | "FISHING"
        | "WATER_SKIING"
        | "INDOOR_RUNNING";
    export const Type = {
        InVehicle: "IN_VEHICLE",
        Biking: "BIKING",
        Still: "STILL",
        Unknown: "UNKNOWN",
        Tilting: "TILTING",
        Walking: "WALKING",
        Running: "RUNNING",
        Aerobics: "AEROBICS",
        Badminton: "BADMINTON",
        Baseball: "BASEBALL",
        Basketball: "BASKETBALL",
        Biathlon: "BIATHLON",
        Handbiking: "HANDBIKING",
        MountainBiking: "MOUNTAIN_BIKING",
        RoadBiking: "ROAD_BIKING",
        Spinning: "SPINNING",
        StationaryBiking: "STATIONARY_BIKING",
        UtilityBiking: "UTILITY_BIKING",
        Boxing: "BOXING",
        Calisthenics: "CALISTHENICS",
        CircuitTraining: "CIRCUIT_TRAINING",
        Cricket: "CRICKET",
        Dancing: "DANCING",
        Elliptical: "ELLIPTICAL",
        Fencing: "FENCING",
        AmericanFootball: "AMERICAN_FOOTBALL",
        AustralianFootball: "AUSTRALIAN_FOOTBALL",
        EnglishFootball: "ENGLISH_FOOTBALL",
        Frisbee: "FRISBEE",
        Gardening: "GARDENING",
        Golf: "GOLF",
        Gymnastics: "GYMNASTICS",
        Handball: "HANDBALL",
        Hiking: "HIKING",
        Hockey: "HOCKEY",
        HorsebackRiding: "HORSEBACK_RIDING",
        Housework: "HOUSEWORK",
        JumpingRope: "JUMPING_ROPE",
        Kayaking: "KAYAKING",
        KettlebellTraining: "KETTLEBELL_TRAINING",
        Kickboxing: "KICKBOXING",
        Kitesurfing: "KITESURFING",
        MartialArts: "MARTIAL_ARTS",
        Meditation: "MEDITATION",
        MixedMartialArts: "MIXED_MARTIAL_ARTS",
        P90XExercises: "P90X_EXERCISES",
        Paragliding: "PARAGLIDING",
        Pilates: "PILATES",
        Polo: "POLO",
        Racquetball: "RACQUETBALL",
        RockClimbing: "ROCK_CLIMBING",
        Rowing: "ROWING",
        RowingMachine: "ROWING_MACHINE",
        Rugby: "RUGBY",
        Jogging: "JOGGING",
        RunningOnSand: "RUNNING_ON_SAND",
        TreadmillRunning: "TREADMILL_RUNNING",
        Sailing: "SAILING",
        ScubaDiving: "SCUBA_DIVING",
        Skateboarding: "SKATEBOARDING",
        Skating: "SKATING",
        CrossSkating: "CROSS_SKATING",
        IndoorRollerblading: "INDOOR_ROLLERBLADING",
        Skiing: "SKIING",
        BackCountrySkiing: "BACK_COUNTRY_SKIING",
        CrossCountrySkiing: "CROSS_COUNTRY_SKIING",
        DownhillSkiing: "DOWNHILL_SKIING",
        KiteSkiing: "KITE_SKIING",
        RollerSkiing: "ROLLER_SKIING",
        Sledding: "SLEDDING",
        Snowboarding: "SNOWBOARDING",
        Snowmobile: "SNOWMOBILE",
        Snowshoeing: "SNOWSHOEING",
        Squash: "SQUASH",
        StairClimbing: "STAIR_CLIMBING",
        StairClimbingMachine: "STAIR_CLIMBING_MACHINE",
        StandUpPaddleboarding: "STAND_UP_PADDLEBOARDING",
        StrengthTraining: "STRENGTH_TRAINING",
        Surfing: "SURFING",
        Swimming: "SWIMMING",
        SwimmingSwimmingPool: "SWIMMING_SWIMMING_POOL",
        SwimmingOpenWater: "SWIMMING_OPEN_WATER",
        TableTennis: "TABLE_TENNIS",
        TeamSports: "TEAM_SPORTS",
        Tennis: "TENNIS",
        Treadmill: "TREADMILL",
        Volleyball: "VOLLEYBALL",
        VolleyballBeach: "VOLLEYBALL_BEACH",
        VolleyballIndoor: "VOLLEYBALL_INDOOR",
        Wakeboarding: "WAKEBOARDING",
        WalkingFitness: "WALKING_FITNESS",
        NordicWalking: "NORDIC_WALKING",
        WalkingTreadmill: "WALKING_TREADMILL",
        Waterpolo: "WATERPOLO",
        Weightlifting: "WEIGHTLIFTING",
        Wheelchair: "WHEELCHAIR",
        Windsurfing: "WINDSURFING",
        Yoga: "YOGA",
        Zumba: "ZUMBA",
        Diving: "DIVING",
        Ergometer: "ERGOMETER",
        IceSkating: "ICE_SKATING",
        IndoorSkating: "INDOOR_SKATING",
        Curling: "CURLING",
        Other: "OTHER",
        Crossfit: "CROSSFIT",
        Hiit: "HIIT",
        IntervalTraining: "INTERVAL_TRAINING",
        WalkingStroller: "WALKING_STROLLER",
        Elevator: "ELEVATOR",
        Escalator: "ESCALATOR",
        Archery: "ARCHERY",
        Softball: "SOFTBALL",
        GuidedBreathing: "GUIDED_BREATHING",
        CardioTraining: "CARDIO_TRAINING",
        Lacrosse: "LACROSSE",
        Stretching: "STRETCHING",
        Triathlon: "TRIATHLON",
        InlineSkating: "INLINE_SKATING",
        SkyDiving: "SKY_DIVING",
        Paddling: "PADDLING",
        Mountaineering: "MOUNTAINEERING",
        Fishing: "FISHING",
        WaterSkiing: "WATER_SKIING",
        IndoorRunning: "INDOOR_RUNNING",
    } as const;
}
