/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export type PlannedWorkoutStepTargets =
    | Terra.PlannedWorkoutStepTargets.PlannedWorkoutStepTarget
    | Terra.PlannedWorkoutStepTargets.CadencePlannedWorkoutStepTarget
    | Terra.PlannedWorkoutStepTargets.HrPlannedWorkoutStepTarget
    | Terra.PlannedWorkoutStepTargets.PowerPlannedWorkoutStepTarget
    | Terra.PlannedWorkoutStepTargets.SpeedPlannedWorkoutStepTarget
    | Terra.PlannedWorkoutStepTargets.PacePlannedWorkoutStepTarget
    | Terra.PlannedWorkoutStepTargets.TssPlannedWorkoutStepTarget
    | Terra.PlannedWorkoutStepTargets.IfPlannedWorkoutStepTarget
    | Terra.PlannedWorkoutStepTargets.RepetitionPlannedWorkoutStepTarget
    | Terra.PlannedWorkoutStepTargets.SwimStrokePlannedWorkoutStepTarget;

export namespace PlannedWorkoutStepTargets {
    export interface PlannedWorkoutStepTarget extends Terra.PlannedWorkoutStepTarget {
        type: "PlannedWorkoutStepTarget";
    }

    export interface CadencePlannedWorkoutStepTarget extends Terra.CadencePlannedWorkoutStepTarget {
        type: "CadencePlannedWorkoutStepTarget";
    }

    export interface HrPlannedWorkoutStepTarget extends Terra.HrPlannedWorkoutStepTarget {
        type: "HRPlannedWorkoutStepTarget";
    }

    export interface PowerPlannedWorkoutStepTarget extends Terra.PowerPlannedWorkoutStepTarget {
        type: "PowerPlannedWorkoutStepTarget";
    }

    export interface SpeedPlannedWorkoutStepTarget extends Terra.SpeedPlannedWorkoutStepTarget {
        type: "SpeedPlannedWorkoutStepTarget";
    }

    export interface PacePlannedWorkoutStepTarget extends Terra.PacePlannedWorkoutStepTarget {
        type: "PacePlannedWorkoutStepTarget";
    }

    export interface TssPlannedWorkoutStepTarget extends Terra.TssPlannedWorkoutStepTarget {
        type: "TSSPlannedWorkoutStepTarget";
    }

    export interface IfPlannedWorkoutStepTarget extends Terra.IfPlannedWorkoutStepTarget {
        type: "IFPlannedWorkoutStepTarget";
    }

    export interface RepetitionPlannedWorkoutStepTarget extends Terra.RepetitionPlannedWorkoutStepTarget {
        type: "RepetitionPlannedWorkoutStepTarget";
    }

    export interface SwimStrokePlannedWorkoutStepTarget extends Terra.SwimStrokePlannedWorkoutStepTarget {
        type: "SwimStrokePlannedWorkoutStepTarget";
    }
}
