/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface PlannedWorkoutStep {
    /** List of targets for the workout */
    targets?: Terra.PlannedWorkoutStepTargets[];
    /** Planned intensity for the workout step */
    intensity?: PlannedWorkoutStep.Intensity;
    /** Position of the workout step in the overall workout */
    order?: number;
    /** Description of workout step */
    description?: string;
    /** List of conditions to be fulfilled for the workout step to be completed - all of the conditions must be completed */
    durations?: Terra.PlannedWorkoutStepDurations[];
    /** Name of workout step */
    name?: string;
}

export namespace PlannedWorkoutStep {
    /**
     * Planned intensity for the workout step
     */
    export type Intensity = "REST" | "WARMUP" | "COOLDOWN" | "RECOVERY" | "INTERVAL" | "ACTIVE";
    export const Intensity = {
        Rest: "REST",
        Warmup: "WARMUP",
        Cooldown: "COOLDOWN",
        Recovery: "RECOVERY",
        Interval: "INTERVAL",
        Active: "ACTIVE",
    } as const;
}
