/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export type PlannedWorkoutStepDurations =
    | Terra.PlannedWorkoutStepDurations.PlannedWorkoutStepDuration
    | Terra.PlannedWorkoutStepDurations.TimePlannedWorkoutStepDuration
    | Terra.PlannedWorkoutStepDurations.PowerAbovePlannedWorkoutStepDuration
    | Terra.PlannedWorkoutStepDurations.PowerBelowPlannedWorkoutStepDuration
    | Terra.PlannedWorkoutStepDurations.FixedRestPlannedWorkoutStepDuration
    | Terra.PlannedWorkoutStepDurations.CaloriesPlannedWorkoutStepDuration
    | Terra.PlannedWorkoutStepDurations.HrAbovePlannedWorkoutStepDuration
    | Terra.PlannedWorkoutStepDurations.HrBelowPlannedWorkoutStepDuration
    | Terra.PlannedWorkoutStepDurations.RepsPlannedWorkoutStepDuration
    | Terra.PlannedWorkoutStepDurations.DistancePlannedWorkoutStepDuration
    | Terra.PlannedWorkoutStepDurations.StepsPlannedWorkoutStepDuration;

export namespace PlannedWorkoutStepDurations {
    export interface PlannedWorkoutStepDuration extends Terra.PlannedWorkoutStepDuration {
        type: "PlannedWorkoutStepDuration";
    }

    export interface TimePlannedWorkoutStepDuration extends Terra.TimePlannedWorkoutStepDuration {
        type: "TimePlannedWorkoutStepDuration";
    }

    export interface PowerAbovePlannedWorkoutStepDuration extends Terra.PowerAbovePlannedWorkoutStepDuration {
        type: "PowerAbovePlannedWorkoutStepDuration";
    }

    export interface PowerBelowPlannedWorkoutStepDuration extends Terra.PowerBelowPlannedWorkoutStepDuration {
        type: "PowerBelowPlannedWorkoutStepDuration";
    }

    export interface FixedRestPlannedWorkoutStepDuration extends Terra.FixedRestPlannedWorkoutStepDuration {
        type: "FixedRestPlannedWorkoutStepDuration";
    }

    export interface CaloriesPlannedWorkoutStepDuration extends Terra.CaloriesPlannedWorkoutStepDuration {
        type: "CaloriesPlannedWorkoutStepDuration";
    }

    export interface HrAbovePlannedWorkoutStepDuration extends Terra.HrAbovePlannedWorkoutStepDuration {
        type: "HRAbovePlannedWorkoutStepDuration";
    }

    export interface HrBelowPlannedWorkoutStepDuration extends Terra.HrBelowPlannedWorkoutStepDuration {
        type: "HRBelowPlannedWorkoutStepDuration";
    }

    export interface RepsPlannedWorkoutStepDuration extends Terra.RepsPlannedWorkoutStepDuration {
        type: "RepsPlannedWorkoutStepDuration";
    }

    export interface DistancePlannedWorkoutStepDuration extends Terra.DistancePlannedWorkoutStepDuration {
        type: "DistancePlannedWorkoutStepDuration";
    }

    export interface StepsPlannedWorkoutStepDuration extends Terra.StepsPlannedWorkoutStepDuration {
        type: "StepsPlannedWorkoutStepDuration";
    }
}
