/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export type PlannedWorkoutSteps =
    | Terra.PlannedWorkoutSteps.PlannedWorkoutStep
    | Terra.PlannedWorkoutSteps.PlannedWorkoutRepeatStep
    | Terra.PlannedWorkoutSteps.SwimmingPlannedWorkoutStep
    | Terra.PlannedWorkoutSteps.CardioPlannedWorkoutStep
    | Terra.PlannedWorkoutSteps.StrengthPlannedWorkoutStep
    | Terra.PlannedWorkoutSteps.YogaPlannedWorkoutStep
    | Terra.PlannedWorkoutSteps.PilatesPlannedWorkoutStep
    | Terra.PlannedWorkoutSteps.RunningPlannedWorkoutStep
    | Terra.PlannedWorkoutSteps.CyclingPlannedWorkoutStep;

export namespace PlannedWorkoutSteps {
    export interface PlannedWorkoutStep extends Terra.PlannedWorkoutStep {
        type: "PlannedWorkoutStep";
    }

    export interface PlannedWorkoutRepeatStep extends Terra.PlannedWorkoutRepeatStep {
        type: "PlannedWorkoutRepeatStep";
    }

    export interface SwimmingPlannedWorkoutStep extends Terra.SwimmingPlannedWorkoutStep {
        type: "SwimmingPlannedWorkoutStep";
    }

    export interface CardioPlannedWorkoutStep extends Terra.CardioPlannedWorkoutStep {
        type: "CardioPlannedWorkoutStep";
    }

    export interface StrengthPlannedWorkoutStep extends Terra.StrengthPlannedWorkoutStep {
        type: "StrengthPlannedWorkoutStep";
    }

    export interface YogaPlannedWorkoutStep extends Terra.YogaPlannedWorkoutStep {
        type: "YogaPlannedWorkoutStep";
    }

    export interface PilatesPlannedWorkoutStep extends Terra.PilatesPlannedWorkoutStep {
        type: "PilatesPlannedWorkoutStep";
    }

    export interface RunningPlannedWorkoutStep extends Terra.RunningPlannedWorkoutStep {
        type: "RunningPlannedWorkoutStep";
    }

    export interface CyclingPlannedWorkoutStep extends Terra.CyclingPlannedWorkoutStep {
        type: "CyclingPlannedWorkoutStep";
    }
}
