/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PolylineMapData {
    /** The polyline representation of the user's trajectory throughout the workout */
    summary_polyline?: string;
}
