/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface PositionData {
    /** Position of the user at the midway point of the workout, represented by a 2-value array of latitude, longitude, wherein each of the two numbers can be nullable. */
    center_pos_lat_lng_deg?: number[];
    /** Position of the user at the end of the workout, represented by a 2-value array of latitude, longitude, wherein each of the two numbers can be nullable. */
    end_pos_lat_lng_deg?: number[];
    /** Array of datapoints of the position of the user, sampled throughout the workout. */
    position_samples?: Terra.PositionSample[];
    /** Position of the user at the start of the workout, represented by a 2-value array of latitude, longitude, wherein each of the two numbers can be nullable. */
    start_pos_lat_lng_deg?: number[];
}
