/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PositionSample {
    timestamp: string;
    coords_lat_lng_deg: number[];
    timer_duration_seconds: number;
}
