/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface PowerData {
    /** Average power output of the user during the workout. */
    avg_watts?: number;
    /** Maximum power output of the user during the workout. */
    max_watts?: number;
    /** Array containing datapoints of the power output of the user sampled throughout the workout. */
    power_samples?: Terra.PowerSample[];
}
