/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Processing event returned when data is being fetched asynchronously
 */
export interface ProcessingEvent {
    type: "processing";
    /** Status of the processing */
    status: "success";
    /** Information about the processing */
    message: string;
    /** User whose data is being processed */
    user: Terra.TerraUser;
    /** Seconds to wait before retrying */
    retry_after_seconds: number;
}
