/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PulseVelocitySample {
    /** Time with which the record is associated, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    timestamp?: string;
    /** User's Pulse Wave Velocity measurement - velocity at which the blood pressure pulse propagates through the circulatory system */
    pulse_wave_velocity_meters_per_second?: number;
}
