/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Rate limit hit event
 */
export interface RateLimitHitEvent {
    type: "rate_limit_hit";
    /** User whose request hit rate limits */
    user: Terra.TerraUser;
    /** Start date of the requested data range */
    start_date: string;
    /** End date of the requested data range */
    end_date: string;
    /** When the request will be retried */
    retrying_at: string;
    /** Information about the rate limit */
    message: string;
}
