/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface ReadinessData {
    /** User's readiness score for a given day, resulting from the sleep session. */
    readiness?: number;
    /** User's recovery score for a given day, resulting from the sleep session - takes Enum value. */
    recovery_level?: Terra.RecoveryLevel;
}
