/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface RequestProcessing {
    /** Recommended time after which the request may be retried */
    retry_after_seconds?: number;
    message?: string;
    type?: string;
    /** Terra User object */
    user?: Terra.TerraUser;
}
