/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface RespirationData {
    /** Object containing information on breathing rate for the sleep session. */
    breaths_data?: Terra.BreathsData;
    /** Object containing information on saturation metrics for the sleep session. */
    oxygen_saturation_data?: Terra.OxygenSaturationData;
    /** Object containing information on snoring metrics for the sleep session. */
    snoring_data?: Terra.SnoringData;
}
