/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RrIntervalSample {
    /** User's RR Interval for a specific heart beat in milliseconds. */
    rr_interval_ms?: number;
    /** Time with which the record is associated, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    timestamp?: string;
    /** The heart beat value at that specific instance. */
    hr_bpm?: number;
}
