/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface RunningPlannedWorkoutStep {
    /** List of targets for the workout */
    targets?: Terra.PlannedWorkoutStepTarget[];
    /** Planned intensity for the workout step */
    intensity?: number;
    /** Position of the workout step in the overall workout */
    order?: number;
    /** Description of workout step */
    description?: string;
    /** List of conditions to be fulfilled for the workout step to be completed - all of the conditions must be completed */
    durations?: Terra.PlannedWorkoutStepDuration[];
    /** Name of workout step */
    name?: string;
}
