/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * S3 Upload event with data download URL
 */
export interface S3PayloadEvent {
    type: "s3_payload";
    /** Status of the upload */
    status: "success";
    /** URL to download the data */
    url: string;
    /** Time in seconds until URL expiration */
    expires_in: number;
}
