/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScoresData {
    /** Activity score for the given day. */
    activity?: number;
    /** Recovery score for the given day. */
    recovery?: number;
    /** Sleep score for the given day, pertaining to the previous night's sleep. */
    sleep?: number;
}
