/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface SleepDataEnrichment {
    sleep_contributors?: Terra.DataContributor[];
    sleep_score?: number;
}
