/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface SleepMetadata {
    /** The end time of the associated sleep session, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    end_time: string;
    /** Flag indicating whether the sleep session was a nap, or the user's main sleep session for the day. */
    is_nap?: boolean;
    /** The start time of the associated sleep session, in ISO8601 format with microsecond precision. Will always fall on midnight of any given day, and will always be equal to 24h before end_time. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    start_time: string;
    /** A unique identifier for the sleep session. */
    summary_id?: string;
    timestamp_localization?: Terra.TimestampLocalization;
    /** The upload type for the associated sleep session, providing information on whether this was an automatic sleep or user-entered. */
    upload_type: Terra.Indeterminate;
}
