/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Sleep data event
 */
export interface SleepEvent {
    type: "sleep";
    /** Array of sleep data */
    data: Terra.Sleep[];
    /** User whose data is being provided */
    user: Terra.TerraUser;
    /** API version */
    version: string;
}
