/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface Sleep {
    /** Object containing additional enrichment data for the sleep session. */
    data_enrichment?: Terra.SleepDataEnrichment;
    /** Object containing information on the device which recorded data for the payload. */
    device_data?: Terra.DeviceData;
    /** Object containing information on the user's heart rate during the sleep session. */
    heart_rate_data?: Terra.HeartRateData;
    /** Object containing daily summary metadata. */
    metadata: Terra.SleepMetadata;
    /** Object containing information on the user's readiness for the day, based off the quality and duration of their sleep. */
    readiness_data?: Terra.ReadinessData;
    /** Object containing information on the user's respiration throughout the sleep session. */
    respiration_data?: Terra.RespirationData;
    /** User's sleep score */
    scores?: Sleep.Scores;
    /** Object containing information on the user's duration spent in various sleep stages. */
    sleep_durations_data?: Terra.SleepDurationsData;
    /** Object containing body temperature information of the user during the sleep recording session. */
    temperature_data?: Terra.SleepTemperatureData;
}

export namespace Sleep {
    /**
     * User's sleep score
     */
    export interface Scores {
        /** User's sleep score. */
        sleep_score?: number;
    }
}
