/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SleepTemperatureData {
    /** Variation in user's skin temperature from their baseline. */
    delta?: number;
}
