/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface SleepDurationsData {
    /** Object containing information on the duration the user spent asleep during the sleep recording session. */
    asleep?: Terra.AsleepDurations;
    /** Object containing information on the duration the user spent awake during the sleep recording session. */
    awake?: Terra.AwakeDurations;
    /** List of sleep stage (Hypnogram) samples recorded during the user's sleep session. */
    hypnogram_samples?: Terra.SleepHypnogramSample[];
    /** Object containing information on the miscellaneous duration data for the sleep recording session. */
    other?: Terra.OtherSleepDurations;
    /** Sleep efficiency of the user given as a percentage, measured as time spent asleep divided by time spent in bed. */
    sleep_efficiency?: number;
}
