/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface SnoringData {
    /** The start time of the recording of snoring data, in ISO8601 format with microsecond precision. Will always fall on midnight of any given day, and will always be equal to 24h before end_time. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    start_time?: string;
    /** The end time of the recording of snoring data, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    end_time?: string;
    /** Number of times over the sleep period when the user started snoring, as determined by the device. */
    num_snoring_events?: number;
    /** List of snoring information data points sampled throughout the sleep session. */
    samples?: Terra.SnoringSample[];
    /** Total duration for which the user was snoring. */
    total_snoring_duration_seconds?: number;
}
