/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SpeedSample {
    timestamp: string;
    speed_meters_per_second: number;
    timer_duration_seconds: number;
}
