/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface StrainData {
    /** Level of cardiovascular strain imposed on the user during the day. */
    strain_level?: number;
}
