/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Stroke type used for the workout step (e.g. breaststroke)
 */
export type StrokeType =
    /**
     * Any swimming stroke style that doesn't fit the standard categories. */
    | "other"
    /**
     * Front crawl stroke where swimmers alternate arm movements with face in water. */
    | "freestyle"
    /**
     * Swimming stroke performed on the back with alternating arm movements. */
    | "backstroke"
    /**
     * Swimming stroke where arms move simultaneously in a heart-shaped pattern with a frog kick. */
    | "breaststroke"
    /**
     * Swimming stroke with simultaneous overhead arm movements and dolphin kick. */
    | "butterfly";
export const StrokeType = {
    Other: "other",
    Freestyle: "freestyle",
    Backstroke: "backstroke",
    Breaststroke: "breaststroke",
    Butterfly: "butterfly",
} as const;
