/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SwimmingData {
    /** Total number of swimming laps performed during the day. */
    num_laps?: number;
    /** Total number of swimming strokes performed during the day. */
    num_strokes?: number;
    /** Pool length for associated with the day. */
    pool_length_meters?: number;
}
