/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface SwimmingPlannedWorkoutStep {
    /** List of targets for the workout */
    targets?: Terra.PlannedWorkoutStepTarget[];
    /** Planned intensity for the workout step */
    intensity?: number;
    /** Position of the workout step in the overall workout */
    order?: number;
    /** Workout equipment to be used during the workout step */
    equipement_type?: SwimmingPlannedWorkoutStep.EquipementType;
    /** Description of workout step */
    description?: string;
    /** List of conditions to be fulfilled for the workout step to be completed - all of the conditions must be completed */
    durations?: Terra.PlannedWorkoutStepDuration[];
    /** Name of workout step */
    name?: string;
    /** Stroke type used for the workout step (e.g. breaststroke) */
    stroke_type?: SwimmingPlannedWorkoutStep.StrokeType;
}

export namespace SwimmingPlannedWorkoutStep {
    /**
     * Workout equipment to be used during the workout step
     */
    export type EquipementType =
        | "NONE"
        | "SWIM_FINS"
        | "SWIM_KICKBOARD"
        | "SWIM_PADDLES"
        | "SWIM_PULL_BUOY"
        | "SWIM_SNORKEL";
    export const EquipementType = {
        None: "NONE",
        SwimFins: "SWIM_FINS",
        SwimKickboard: "SWIM_KICKBOARD",
        SwimPaddles: "SWIM_PADDLES",
        SwimPullBuoy: "SWIM_PULL_BUOY",
        SwimSnorkel: "SWIM_SNORKEL",
    } as const;
    /**
     * Stroke type used for the workout step (e.g. breaststroke)
     */
    export type StrokeType = "OTHER" | "FREESTYLE" | "BACKSTROKE" | "BREASTSTROKE" | "BUTTERFLY" | "REST";
    export const StrokeType = {
        Other: "OTHER",
        Freestyle: "FREESTYLE",
        Backstroke: "BACKSTROKE",
        Breaststroke: "BREASTSTROKE",
        Butterfly: "BUTTERFLY",
        Rest: "REST",
    } as const;
}
