/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface TagData {
    /** Array of user-entered tags for the day. */
    tags?: Terra.TagEntry[];
}
