/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TagEntry {
    /** Time with which the tag is associated, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    timestamp: string;
    /** Tag name, representing a certain event associated with the user's day. */
    tag_name: string;
    /** User-input notes associated with the given tag. */
    notes: string;
}
