/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface TemperatureData {
    /** List of ambient temperature measurements sampled throughout the day. */
    ambient_temperature_samples?: Terra.TemperatureSample[];
    /** List of body temperature measurements sampled throughout the day. */
    body_temperature_samples?: Terra.TemperatureSample[];
    /** List of skin temperature measurements sampled throughout the day. */
    skin_temperature_samples?: Terra.TemperatureSample[];
}
