/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TerraUser {
    /** Terra identifier for the wearable connection */
    user_id: string;
    /** Connection data source */
    provider: string;
    /** Last time at which a webhook update was sent for the connection */
    last_webhook_update?: string;
    /** (when available) Permissions granted by the user during authentication - to be used as debugging metadata */
    scopes?: string;
    /** Connection identifier on the developer's end, used to tie connection back to a user on the developer's platform */
    reference_id?: string;
    /** whether the user is active or not (inactive users will not receive any data updates and are in considered */
    active?: boolean;
}
