/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates whether the timestamps in this payload are localized (LOCAL) or in UTC.
 */
export type TimestampLocalization = number;
