/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TorqueSample {
    timestamp: string;
    timer_duration_seconds: number;
    torque_newton_meters: number;
}
