/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export interface TssData {
    /** Array of TSS information sampled throughout the workout */
    TSS_samples?: Terra.TssSample[];
}
