/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TssSample {
    planned?: number;
    actual?: number;
    method?: string;
    intensity_factor_planned?: number;
    intensity_factor_actual?: number;
    normalized_power_watts?: number;
}
