/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UnauthorizedErrorBody {
    /** a detailed message describing the error */
    message?: string;
    /** indicates that an error happened (value is error) */
    status?: UnauthorizedErrorBody.Status;
}

export namespace UnauthorizedErrorBody {
    /**
     * indicates that an error happened (value is error)
     */
    export type Status = "success" | "error";
    export const Status = {
        Success: "success",
        Error: "error",
    } as const;
}
