/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * User re-authentication event
 */
export interface UserReauthEvent {
    type: "user_reauth";
    /** The new user record */
    new_user: Terra.TerraUser;
    /** The old user record that will be deleted */
    old_user: Terra.TerraUser;
    /** Status of the re-authentication */
    status: "warning";
    /** Information about the re-authentication */
    message: string;
}
