/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

export type UserAuthWebhookPayload = Terra.UserAuthWebhookPayload.Success | Terra.UserAuthWebhookPayload.Error_;

export namespace UserAuthWebhookPayload {
    export interface Success extends Terra.AuthSuccessEvent {
        status: "success";
    }

    export interface Error_ extends Terra.AuthErrorEvent {
        status: "error";
    }
}
