/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Vo2MaxSample {
    /** Time with which the record is associated, in ISO8601 format with microsecond precision. TimeZone info will be provided whenever possible. If absent, the time corresponds to the user's local time. */
    timestamp?: string;
    /** User's VO2Max - maximum amount of oxygen the user's body can utilize during exercise */
    vo2max_ml_per_min_per_kg?: number;
}
