/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Base webhook event structure that all events extend from
 */
export interface WebhookEvent {
    /** The type of event */
    type: string;
}
