/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../index.js";

/**
 * Union of all possible webhook event types
 */
export type WebhookEventType =
    | Terra.HealthcheckEvent
    | Terra.AuthSuccessEvent
    | Terra.AuthErrorEvent
    | Terra.DeauthEvent
    | Terra.UserReauthEvent
    | Terra.AccessRevokedEvent
    | Terra.ConnectionErrorEvent
    | Terra.GoogleNoDatasourceEvent
    | Terra.PermissionChangeEvent
    | Terra.ProcessingEvent
    | Terra.LargeRequestProcessingEvent
    | Terra.LargeRequestSendingEvent
    | Terra.RateLimitHitEvent
    | Terra.ActivityEvent
    | Terra.AthleteEvent
    | Terra.BodyEvent
    | Terra.DailyEvent
    | Terra.MenstruationEvent
    | Terra.NutritionEvent
    | Terra.SleepEvent
    | Terra.S3PayloadEvent;
