/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WorkData {
    /** Total work output of the user for the workout, in kilojoules. */
    work_kilojoules?: number;
}
