/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface IntegrationsDetailedFetchRequest {
    /**
     * If `true`, allows SDK integrations to be included in the response.
     */
    sdk?: boolean;
}
