/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../../../../index.js";

/**
 * @example
 *     {
 *         data: [{}]
 *     }
 */
export interface PlannedWorkoutWriteRequest {
    /** PlannedWorkout entry to post to data provider */
    data: Terra.PlannedWorkout[];
}
