/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         resource: "resource"
 *     }
 */
export interface AuthenticationAuthenticateUserRequest {
    /**
     * resource to authenticate user with
     */
    resource: string;
    language?: string;
    reference_id?: string;
    auth_success_redirect_url?: string;
    auth_failure_redirect_url?: string;
}
