/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         resource: "FITBIT"
 *     }
 */
export interface AuthenticationAuthenticateUserRequest {
    /**
     * Provider resource identifier (e.g., 'FITBIT', 'GARMIN', 'OURA'). See "Get detailed list of integrations" for available providers
     */
    resource: string;
    language?: string;
    reference_id?: string;
    auth_success_redirect_url?: string;
    auth_failure_redirect_url?: string;
}
