/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface WidgetSessionParams {
    /** Comma separated list of providers to display on the device selection page. This overrides your selected sources on your dashboard */
    providers?: string;
    /** Display language of the widget */
    language?: string;
    /** Identifier of the end user on your system, such as a user ID or email associated with them */
    reference_id?: string;
    /** URL the user is redirected to upon successful authentication */
    auth_success_redirect_url?: string;
    /** URL the user is redirected to upon unsuccessful authentication */
    auth_failure_redirect_url?: string;
}
