/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../../../index.js";

export interface UserModifyUserResponse {
    user?: Terra.TerraUser;
    /** Indicates that the request was successful */
    status?: UserModifyUserResponse.Status;
}

export namespace UserModifyUserResponse {
    /**
     * Indicates that the request was successful
     */
    export type Status = "success" | "error";
    export const Status = {
        Success: "success",
        Error: "error",
    } as const;
}
