/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../../../index.js";

export type UserGetAllUserIDsResponse =
    | {
          users?: Terra.TerraUser[] | undefined;
      }
    | {
          data?:
              | {
                    next?: number | undefined;
                    max_page?: number | undefined;
                    results?: Terra.TerraUser[] | undefined;
                }
              | undefined;
      };
