/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../../../index.js";

export type UserGetInfoForUserIdResponse =
    /**
     * User information for one connection (single User object) */
    | {
          user?: Terra.TerraUser | undefined;
          status?: ("success" | "error") | undefined;
          is_authenticated?: boolean | undefined;
      }
    /**
     * List of multiple User objects the reference_id is associated to */
    | Terra.TerraUser[];
