/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AuthenticationGenerateWidgetSessionResponse {
    /** Session ID for the widget authentication session */
    session_id?: string;
    /** the widget URL the user must be redirected to in order to link their account */
    url?: string;
    /** indicates that the request was successful (value is success) */
    status?: AuthenticationGenerateWidgetSessionResponse.Status;
    /** a number in seconds depicting how long the url is valid for */
    expires_in?: number;
}

export namespace AuthenticationGenerateWidgetSessionResponse {
    /**
     * indicates that the request was successful (value is success)
     */
    export type Status = "success" | "error";
    export const Status = {
        Success: "success",
        Error: "error",
    } as const;
}
