/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AuthenticationGenerateAuthTokenResponse {
    status?: string;
    token?: string;
    expires_in?: number;
}
