/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AuthenticationDeauthenticateUserResponse {
    /** indicates that the deauthentication was successful (value is success) */
    status?: AuthenticationDeauthenticateUserResponse.Status;
}

export namespace AuthenticationDeauthenticateUserResponse {
    /**
     * indicates that the deauthentication was successful (value is success)
     */
    export type Status = "success" | "error";
    export const Status = {
        Success: "success",
        Error: "error",
    } as const;
}
