/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         user_id: "user_id"
 *     }
 */
export interface AthleteFetchRequest {
    /**
     * user ID to query data for
     */
    user_id: string;
    /**
     * boolean flag specifying whether to send the data retrieved to the webhook, or in the response
     */
    to_webhook?: boolean;
}
