/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         user_id: "user_id"
 *     }
 */
export interface AthleteFetchRequest {
    /** Terra user ID (UUID format) to retrieve data for */
    user_id: string;
    /** Boolean flag specifying whether to send the data retrieved to the webhook instead of in the response (default: false) */
    to_webhook?: boolean;
}
