/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../../../../index.js";

/**
 * @example
 *     {
 *         user_id: "user_id",
 *         start_date: 1
 *     }
 */
export interface NutritionFetchRequest {
    /**
     * user ID to query data for
     */
    user_id: string;
    /**
     * start date of data to query for - either ISO8601 date or unix timestamp
     */
    start_date: Terra.NutritionFetchRequestStartDate;
    /**
     * end date of data to query for - either ISO8601 date or unix timestamp
     */
    end_date?: number;
    /**
     * boolean flag specifying whether to send the data retrieved to the webhook, or in the response
     */
    to_webhook?: boolean;
    /**
     * boolean flag specifying whether to include detailed samples in the returned payload
     */
    with_samples?: boolean;
}
