/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../../../../index.js";

/**
 * @example
 *     {
 *         data: [{
 *                 metadata: {
 *                     end_time: "2022-10-28T10:00:00.000000+01:00",
 *                     start_time: "1999-11-23T09:00:00.000000+02:00"
 *                 }
 *             }]
 *     }
 */
export interface NutritionWriteRequest {
    /** Nutrition entry to post to data provider */
    data: Terra.Nutrition[];
}
