/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../../../index.js";

export type AthleteFetchResponse =
    | Terra.AthleteFetchResponse.Athlete
    | Terra.AthleteFetchResponse.NoData
    | Terra.AthleteFetchResponse.Webhook;

export namespace AthleteFetchResponse {
    export interface Athlete extends Terra.AthleteCollection {
        type: "athlete";
    }

    export interface NoData extends Terra.NoDataReturned {
        type: "no_data";
    }

    export interface Webhook extends Terra.DataSentToWebhook {
        type: "webhook";
    }
}
