/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { TerraClient } from "../../src/Client";
import * as Terra from "../../src/api/index";

describe("Body", () => {
    test("fetch (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });

        const rawResponseBody = {
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            data: [
                {
                    device_data: {
                        activation_timestamp: "2022-12-25T00:00:00.000000+05:00",
                        hardware_version: "v2.1",
                        manufacturer: "Garmin",
                        name: "Forerunner 945",
                        serial_number: "GR123456789",
                        software_version: "5.2.1",
                    },
                    hydration_data: { day_total_water_consumption_ml: 2500 },
                    metadata: {
                        end_time: "2022-10-28T10:00:00.000000+01:00",
                        start_time: "1999-11-23T09:00:00.000000+02:00",
                        timestamp_localization: 0,
                    },
                    oxygen_data: { avg_saturation_percentage: 98, vo2max_ml_per_min_per_kg: 45.5 },
                    glucose_data: { day_avg_blood_glucose_mg_per_dL: 92.5 },
                },
            ],
            type: "type",
        };
        server.mockEndpoint().get("/body").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.body.fetch({
            user_id: "user_id",
            start_date: 1,
        });
        expect(response).toEqual({
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            data: [
                {
                    device_data: {
                        activation_timestamp: "2022-12-25T00:00:00.000000+05:00",
                        hardware_version: "v2.1",
                        manufacturer: "Garmin",
                        name: "Forerunner 945",
                        serial_number: "GR123456789",
                        software_version: "5.2.1",
                    },
                    hydration_data: {
                        day_total_water_consumption_ml: 2500,
                    },
                    metadata: {
                        end_time: "2022-10-28T10:00:00.000000+01:00",
                        start_time: "1999-11-23T09:00:00.000000+02:00",
                        timestamp_localization: 0,
                    },
                    oxygen_data: {
                        avg_saturation_percentage: 98,
                        vo2max_ml_per_min_per_kg: 45.5,
                    },
                    glucose_data: {
                        day_avg_blood_glucose_mg_per_dL: 92.5,
                    },
                },
            ],
            type: "type",
        });
    });

    test("fetch (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/body").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.body.fetch({
                user_id: "user_id",
                start_date: 1,
            });
        }).rejects.toThrow(
            new Terra.BadRequestError({
                key: "value",
            }),
        );
    });

    test("fetch (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/body").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.body.fetch({
                user_id: "user_id",
                start_date: 1,
            });
        }).rejects.toThrow(
            new Terra.UnauthorizedError({
                key: "value",
            }),
        );
    });

    test("fetch (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/body").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.body.fetch({
                user_id: "user_id",
                start_date: 1,
            });
        }).rejects.toThrow(
            new Terra.NotFoundError({
                key: "value",
            }),
        );
    });

    test("write (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    metadata: {
                        end_time: "2022-10-28T10:00:00.000000+01:00",
                        start_time: "1999-11-23T09:00:00.000000+02:00",
                    },
                },
            ],
        };
        const rawResponseBody = {
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            log_ids: ["log_ids"],
            message: "message",
        };
        server
            .mockEndpoint()
            .post("/body")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.body.write({
            data: [
                {
                    metadata: {
                        end_time: "2022-10-28T10:00:00.000000+01:00",
                        start_time: "1999-11-23T09:00:00.000000+02:00",
                    },
                },
            ],
        });
        expect(response).toEqual({
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            log_ids: ["log_ids"],
            message: "message",
        });
    });

    test("write (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    blood_pressure_data: undefined,
                    device_data: undefined,
                    heart_data: undefined,
                    hydration_data: undefined,
                    ketone_data: undefined,
                    measurements_data: undefined,
                    metadata: { end_time: "end_time", start_time: "start_time", timestamp_localization: undefined },
                    oxygen_data: undefined,
                    temperature_data: undefined,
                    glucose_data: undefined,
                },
                {
                    blood_pressure_data: undefined,
                    device_data: undefined,
                    heart_data: undefined,
                    hydration_data: undefined,
                    ketone_data: undefined,
                    measurements_data: undefined,
                    metadata: { end_time: "end_time", start_time: "start_time", timestamp_localization: undefined },
                    oxygen_data: undefined,
                    temperature_data: undefined,
                    glucose_data: undefined,
                },
            ],
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/body")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.body.write({
                data: [
                    {
                        blood_pressure_data: undefined,
                        device_data: undefined,
                        heart_data: undefined,
                        hydration_data: undefined,
                        ketone_data: undefined,
                        measurements_data: undefined,
                        metadata: {
                            end_time: "end_time",
                            start_time: "start_time",
                            timestamp_localization: undefined,
                        },
                        oxygen_data: undefined,
                        temperature_data: undefined,
                        glucose_data: undefined,
                    },
                    {
                        blood_pressure_data: undefined,
                        device_data: undefined,
                        heart_data: undefined,
                        hydration_data: undefined,
                        ketone_data: undefined,
                        measurements_data: undefined,
                        metadata: {
                            end_time: "end_time",
                            start_time: "start_time",
                            timestamp_localization: undefined,
                        },
                        oxygen_data: undefined,
                        temperature_data: undefined,
                        glucose_data: undefined,
                    },
                ],
            });
        }).rejects.toThrow(
            new Terra.BadRequestError({
                key: "value",
            }),
        );
    });

    test("write (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    blood_pressure_data: undefined,
                    device_data: undefined,
                    heart_data: undefined,
                    hydration_data: undefined,
                    ketone_data: undefined,
                    measurements_data: undefined,
                    metadata: { end_time: "end_time", start_time: "start_time", timestamp_localization: undefined },
                    oxygen_data: undefined,
                    temperature_data: undefined,
                    glucose_data: undefined,
                },
                {
                    blood_pressure_data: undefined,
                    device_data: undefined,
                    heart_data: undefined,
                    hydration_data: undefined,
                    ketone_data: undefined,
                    measurements_data: undefined,
                    metadata: { end_time: "end_time", start_time: "start_time", timestamp_localization: undefined },
                    oxygen_data: undefined,
                    temperature_data: undefined,
                    glucose_data: undefined,
                },
            ],
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/body")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.body.write({
                data: [
                    {
                        blood_pressure_data: undefined,
                        device_data: undefined,
                        heart_data: undefined,
                        hydration_data: undefined,
                        ketone_data: undefined,
                        measurements_data: undefined,
                        metadata: {
                            end_time: "end_time",
                            start_time: "start_time",
                            timestamp_localization: undefined,
                        },
                        oxygen_data: undefined,
                        temperature_data: undefined,
                        glucose_data: undefined,
                    },
                    {
                        blood_pressure_data: undefined,
                        device_data: undefined,
                        heart_data: undefined,
                        hydration_data: undefined,
                        ketone_data: undefined,
                        measurements_data: undefined,
                        metadata: {
                            end_time: "end_time",
                            start_time: "start_time",
                            timestamp_localization: undefined,
                        },
                        oxygen_data: undefined,
                        temperature_data: undefined,
                        glucose_data: undefined,
                    },
                ],
            });
        }).rejects.toThrow(
            new Terra.NotFoundError({
                key: "value",
            }),
        );
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            processed_data: [{ id: "id", response_code: 1 }],
        };
        server
            .mockEndpoint()
            .delete("/body")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.body.delete({
            user_id: "user_id",
        });
        expect(response).toEqual({
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            processed_data: [
                {
                    id: "id",
                    response_code: 1,
                },
            ],
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });
        const rawRequestBody = { log_ids: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/body")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.body.delete({
                user_id: "user_id",
                log_ids: undefined,
            });
        }).rejects.toThrow(
            new Terra.BadRequestError({
                key: "value",
            }),
        );
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });
        const rawRequestBody = { log_ids: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/body")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.body.delete({
                user_id: "user_id",
                log_ids: undefined,
            });
        }).rejects.toThrow(
            new Terra.UnauthorizedError({
                key: "value",
            }),
        );
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });
        const rawRequestBody = { log_ids: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/body")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.body.delete({
                user_id: "user_id",
                log_ids: undefined,
            });
        }).rejects.toThrow(
            new Terra.NotFoundError({
                key: "value",
            }),
        );
    });
});
