/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { TerraClient } from "../../src/Client";

describe("Daily", () => {
    test("fetch", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });

        const rawResponseBody = {
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            data: [
                {
                    active_durations_data: {
                        activity_seconds: 1800,
                        inactivity_seconds: 600,
                        low_intensity_seconds: 900,
                        moderate_intensity_seconds: 600,
                        num_continuous_inactive_periods: 3,
                        rest_seconds: 120,
                        vigorous_intensity_seconds: 300,
                    },
                    device_data: {
                        activation_timestamp: "2022-12-25T00:00:00.000000+05:00",
                        hardware_version: "v2.1",
                        manufacturer: "Garmin",
                        name: "Forerunner 945",
                        serial_number: "GR123456789",
                        software_version: "5.2.1",
                    },
                    distance_data: { distance_meters: 8500, floors_climbed: 15, steps: 12000 },
                    MET_data: {
                        avg_level: 3.8,
                        num_high_intensity_minutes: 10,
                        num_inactive_minutes: 5,
                        num_low_intensity_minutes: 15,
                        num_moderate_intensity_minutes: 25,
                    },
                    metadata: {
                        end_time: "2022-10-28T10:00:00.000000+01:00",
                        start_time: "1999-11-23T09:00:00.000000+02:00",
                        timestamp_localization: 0,
                        upload_type: 1.1,
                    },
                    oxygen_data: { avg_saturation_percentage: 98, vo2max_ml_per_min_per_kg: 45.5 },
                    scores: { activity: 92, recovery: 78, sleep: 85 },
                    strain_data: { strain_level: 14.5 },
                    stress_data: {
                        avg_stress_level: 45.5,
                        activity_stress_duration_seconds: 3600,
                        low_stress_duration_seconds: 28800,
                        max_stress_level: 85,
                        medium_stress_duration_seconds: 7200,
                        rest_stress_duration_seconds: 1800,
                        high_stress_duration_seconds: 900,
                        stress_duration_seconds: 5400,
                    },
                    tag_data: {
                        tags: [
                            {
                                timestamp: "1999-11-23T09:00:00.000000+02:00",
                                tag_name: "hot_shower",
                                notes: "Felt refreshed after",
                            },
                        ],
                    },
                },
            ],
            type: "type",
        };
        server.mockEndpoint().get("/daily").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.daily.fetch({
            user_id: "user_id",
            start_date: 1,
        });
        expect(response).toEqual({
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            data: [
                {
                    active_durations_data: {
                        activity_seconds: 1800,
                        inactivity_seconds: 600,
                        low_intensity_seconds: 900,
                        moderate_intensity_seconds: 600,
                        num_continuous_inactive_periods: 3,
                        rest_seconds: 120,
                        vigorous_intensity_seconds: 300,
                    },
                    device_data: {
                        activation_timestamp: "2022-12-25T00:00:00.000000+05:00",
                        hardware_version: "v2.1",
                        manufacturer: "Garmin",
                        name: "Forerunner 945",
                        serial_number: "GR123456789",
                        software_version: "5.2.1",
                    },
                    distance_data: {
                        distance_meters: 8500,
                        floors_climbed: 15,
                        steps: 12000,
                    },
                    MET_data: {
                        avg_level: 3.8,
                        num_high_intensity_minutes: 10,
                        num_inactive_minutes: 5,
                        num_low_intensity_minutes: 15,
                        num_moderate_intensity_minutes: 25,
                    },
                    metadata: {
                        end_time: "2022-10-28T10:00:00.000000+01:00",
                        start_time: "1999-11-23T09:00:00.000000+02:00",
                        timestamp_localization: 0,
                        upload_type: 1.1,
                    },
                    oxygen_data: {
                        avg_saturation_percentage: 98,
                        vo2max_ml_per_min_per_kg: 45.5,
                    },
                    scores: {
                        activity: 92,
                        recovery: 78,
                        sleep: 85,
                    },
                    strain_data: {
                        strain_level: 14.5,
                    },
                    stress_data: {
                        avg_stress_level: 45.5,
                        activity_stress_duration_seconds: 3600,
                        low_stress_duration_seconds: 28800,
                        max_stress_level: 85,
                        medium_stress_duration_seconds: 7200,
                        rest_stress_duration_seconds: 1800,
                        high_stress_duration_seconds: 900,
                        stress_duration_seconds: 5400,
                    },
                    tag_data: {
                        tags: [
                            {
                                timestamp: "1999-11-23T09:00:00.000000+02:00",
                                tag_name: "hot_shower",
                                notes: "Felt refreshed after",
                            },
                        ],
                    },
                },
            ],
            type: "type",
        });
    });
});
