/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { TerraClient } from "../../src/Client";

describe("Integrations", () => {
    test("fetch", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });

        const rawResponseBody = { providers: ["FITBIT"], sdk_resource: ["APPLE"], status: "success" };
        server.mockEndpoint().get("/integrations").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.integrations.fetch();
        expect(response).toEqual({
            providers: ["FITBIT"],
            sdk_resource: ["APPLE"],
            status: "success",
        });
    });

    test("detailedfetch", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "success",
            providers: [
                {
                    provider: "MAPMYFITNESS",
                    name: "MapMyFitness",
                    icon: "https://api.tryterra.co/v2/static/assets/img/app_icons/mapmyfitness.webp",
                    setup: "API_KEYS_MANAGED",
                    enabled: true,
                    types: {
                        activity: true,
                        body: false,
                        nutrition: false,
                        daily: false,
                        sleep: false,
                        menstruation: false,
                    },
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/integrations/detailed")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.integrations.detailedfetch();
        expect(response).toEqual({
            status: "success",
            providers: [
                {
                    provider: "MAPMYFITNESS",
                    name: "MapMyFitness",
                    icon: "https://api.tryterra.co/v2/static/assets/img/app_icons/mapmyfitness.webp",
                    setup: "API_KEYS_MANAGED",
                    enabled: true,
                    types: {
                        activity: true,
                        body: false,
                        nutrition: false,
                        daily: false,
                        sleep: false,
                        menstruation: false,
                    },
                },
            ],
        });
    });
});
