/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { TerraClient } from "../../src/Client";

describe("Menstruation", () => {
    test("fetch", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });

        const rawResponseBody = {
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            data: [
                {
                    metadata: {
                        end_time: "2022-10-28T10:00:00.000000+01:00",
                        start_time: "1999-11-23T09:00:00.000000+02:00",
                        timestamp_localization: 0,
                    },
                    menstruation_data: {
                        period_length_days: 5,
                        length_of_current_phase_days: 5,
                        days_until_next_phase: 23,
                        period_start_date: "2022-11-28",
                        predicted_cycle_length_days: 28,
                        day_in_cycle: 24,
                        last_updated_time: "2022-12-12T14:03:05.000000-05:00",
                        cycle_length_days: "28",
                        is_predicted_cycle: "true",
                    },
                },
            ],
            type: "type",
        };
        server.mockEndpoint().get("/menstruation").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.menstruation.fetch({
            user_id: "user_id",
            start_date: 1,
        });
        expect(response).toEqual({
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            data: [
                {
                    metadata: {
                        end_time: "2022-10-28T10:00:00.000000+01:00",
                        start_time: "1999-11-23T09:00:00.000000+02:00",
                        timestamp_localization: 0,
                    },
                    menstruation_data: {
                        period_length_days: 5,
                        length_of_current_phase_days: 5,
                        days_until_next_phase: 23,
                        period_start_date: "2022-11-28",
                        predicted_cycle_length_days: 28,
                        day_in_cycle: 24,
                        last_updated_time: "2022-12-12T14:03:05.000000-05:00",
                        cycle_length_days: "28",
                        is_predicted_cycle: "true",
                    },
                },
            ],
            type: "type",
        });
    });
});
