/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { TerraClient } from "../../src/Client";

describe("Nutrition", () => {
    test("fetch", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });

        const rawResponseBody = {
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            data: [
                {
                    drink_samples: [
                        {
                            timestamp: "2022-11-23T09:00:00.000000+02:00",
                            drink_volume: 250,
                            drink_unit: "ml",
                            drink_name: "Water",
                        },
                    ],
                    meals: [
                        {
                            micros: {
                                biotin_mg: 0.03,
                                caffeine_mg: 95,
                                calcium_mg: 1000,
                                chloride_mg: 2300,
                                chromium_mg: 0.035,
                                copper_mg: 0.9,
                                folate_mg: 0.4,
                                folic_acid_mg: 0.4,
                                iodine_mg: 0.15,
                                iron_mg: 8.5,
                                magnesium_mg: 320,
                                manganese_mg: 2.3,
                                molybdenum_mg: 0.045,
                                niacin_mg: 16,
                                pantothenic_acid_mg: 5,
                                phosphorus_mg: 1000,
                                potassium_mg: 3500,
                                riboflavin_mg: 1.3,
                                selenium_mg: 0.055,
                                thiamin_mg: 1.2,
                                vitamin_A_mg: 0.9,
                                vitamin_B12_mg: 0.0024,
                                vitamin_B6_mg: 1.7,
                                vitamin_C_mg: 90,
                                vitamin_D_mg: 0.02,
                                vitamin_D2_mg: 0.01,
                                vitamin_D3_mg: 0.015,
                                vitamin_E_mg: 15,
                                vitamin_K_mg: 0.12,
                                zinc_mg: 11,
                                cystine_g: 0.3,
                                histidine_g: 0.6,
                                isoleucine_g: 0.8,
                                leucine_g: 1.2,
                                lysine_g: 0.9,
                                methionine_g: 0.6,
                                phenylalanine_g: 0.9,
                                threonine_g: 0.5,
                                tryptophan_g: 0.3,
                                tyrosine_g: 0.7,
                                valine_g: 0.8,
                                monounsaturated_fat_g: 15,
                                polyunsaturated_fat_g: 13,
                                omega3_g: 1.6,
                                omega6_g: 17,
                                starch_g: 25,
                            },
                            type: 1.1,
                            id: "food_123",
                            timestamp: "2022-12-12T08:53:00.000000+02:00",
                            quantity: { unit: 1.1, amount: 1.1 },
                            name: "Oatmeal",
                            macros: {
                                alcohol_g: 14,
                                calories: 2000,
                                carbohydrates_g: 300,
                                cholesterol_mg: 300,
                                fat_g: 65,
                                fiber_g: 25,
                                net_carbohydrates_g: 275,
                                protein_g: 50,
                                saturated_fat_g: 20,
                                sodium_mg: 2300,
                                sugar_g: 25,
                                trans_fat_g: 2,
                            },
                        },
                    ],
                    metadata: {
                        end_time: "2022-10-28T10:00:00.000000+01:00",
                        start_time: "1999-11-23T09:00:00.000000+02:00",
                        timestamp_localization: 0,
                    },
                    summary: { water_ml: 2000, drink_ml: 500 },
                },
            ],
            type: "type",
        };
        server.mockEndpoint().get("/nutrition").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.nutrition.fetch({
            user_id: "user_id",
            start_date: 1,
        });
        expect(response).toEqual({
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            data: [
                {
                    drink_samples: [
                        {
                            timestamp: "2022-11-23T09:00:00.000000+02:00",
                            drink_volume: 250,
                            drink_unit: "ml",
                            drink_name: "Water",
                        },
                    ],
                    meals: [
                        {
                            micros: {
                                biotin_mg: 0.03,
                                caffeine_mg: 95,
                                calcium_mg: 1000,
                                chloride_mg: 2300,
                                chromium_mg: 0.035,
                                copper_mg: 0.9,
                                folate_mg: 0.4,
                                folic_acid_mg: 0.4,
                                iodine_mg: 0.15,
                                iron_mg: 8.5,
                                magnesium_mg: 320,
                                manganese_mg: 2.3,
                                molybdenum_mg: 0.045,
                                niacin_mg: 16,
                                pantothenic_acid_mg: 5,
                                phosphorus_mg: 1000,
                                potassium_mg: 3500,
                                riboflavin_mg: 1.3,
                                selenium_mg: 0.055,
                                thiamin_mg: 1.2,
                                vitamin_A_mg: 0.9,
                                vitamin_B12_mg: 0.0024,
                                vitamin_B6_mg: 1.7,
                                vitamin_C_mg: 90,
                                vitamin_D_mg: 0.02,
                                vitamin_D2_mg: 0.01,
                                vitamin_D3_mg: 0.015,
                                vitamin_E_mg: 15,
                                vitamin_K_mg: 0.12,
                                zinc_mg: 11,
                                cystine_g: 0.3,
                                histidine_g: 0.6,
                                isoleucine_g: 0.8,
                                leucine_g: 1.2,
                                lysine_g: 0.9,
                                methionine_g: 0.6,
                                phenylalanine_g: 0.9,
                                threonine_g: 0.5,
                                tryptophan_g: 0.3,
                                tyrosine_g: 0.7,
                                valine_g: 0.8,
                                monounsaturated_fat_g: 15,
                                polyunsaturated_fat_g: 13,
                                omega3_g: 1.6,
                                omega6_g: 17,
                                starch_g: 25,
                            },
                            type: 1.1,
                            id: "food_123",
                            timestamp: "2022-12-12T08:53:00.000000+02:00",
                            quantity: {
                                unit: 1.1,
                                amount: 1.1,
                            },
                            name: "Oatmeal",
                            macros: {
                                alcohol_g: 14,
                                calories: 2000,
                                carbohydrates_g: 300,
                                cholesterol_mg: 300,
                                fat_g: 65,
                                fiber_g: 25,
                                net_carbohydrates_g: 275,
                                protein_g: 50,
                                saturated_fat_g: 20,
                                sodium_mg: 2300,
                                sugar_g: 25,
                                trans_fat_g: 2,
                            },
                        },
                    ],
                    metadata: {
                        end_time: "2022-10-28T10:00:00.000000+01:00",
                        start_time: "1999-11-23T09:00:00.000000+02:00",
                        timestamp_localization: 0,
                    },
                    summary: {
                        water_ml: 2000,
                        drink_ml: 500,
                    },
                },
            ],
            type: "type",
        });
    });

    test("write", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });
        const rawRequestBody = {
            data: [
                {
                    metadata: {
                        end_time: "2022-10-28T10:00:00.000000+01:00",
                        start_time: "1999-11-23T09:00:00.000000+02:00",
                    },
                },
            ],
        };
        const rawResponseBody = {
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            log_ids: ["log_ids"],
            message: "message",
        };
        server
            .mockEndpoint()
            .post("/nutrition")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.nutrition.write({
            data: [
                {
                    metadata: {
                        end_time: "2022-10-28T10:00:00.000000+01:00",
                        start_time: "1999-11-23T09:00:00.000000+02:00",
                    },
                },
            ],
        });
        expect(response).toEqual({
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            log_ids: ["log_ids"],
            message: "message",
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            processed_data: [{ id: "id", response_code: 1 }],
        };
        server
            .mockEndpoint()
            .delete("/nutrition")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.nutrition.delete({
            user_id: "user_id",
        });
        expect(response).toEqual({
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            processed_data: [
                {
                    id: "id",
                    response_code: 1,
                },
            ],
        });
    });
});
