/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { TerraClient } from "../../src/Client";
import * as Terra from "../../src/api/index";

describe("Sleep", () => {
    test("fetch (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });

        const rawResponseBody = {
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            data: [
                {
                    device_data: {
                        activation_timestamp: "2022-12-25T00:00:00.000000+05:00",
                        hardware_version: "v2.1",
                        manufacturer: "Garmin",
                        name: "Forerunner 945",
                        serial_number: "GR123456789",
                        software_version: "5.2.1",
                    },
                    metadata: {
                        end_time: "2022-11-24T08:00:00.000000+01:00",
                        is_nap: false,
                        start_time: "1999-11-23T22:00:00.000000+02:00",
                        timestamp_localization: 0,
                        upload_type: 1.1,
                    },
                    readiness_data: { readiness: 85 },
                    sleep_durations_data: { sleep_efficiency: 87.5 },
                    temperature_data: { delta: 0.5 },
                },
            ],
            type: "type",
        };
        server.mockEndpoint().get("/sleep").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.sleep.fetch({
            user_id: "user_id",
            start_date: 1,
        });
        expect(response).toEqual({
            user: {
                user_id: "123e4567-e89b-12d3-a456-426614174000",
                provider: "FITBIT",
                last_webhook_update: "2022-12-12T10:00:00.000000+00:00",
                scopes: "activity:read,sleep:read",
                reference_id: "user123@email.com",
                active: true,
            },
            data: [
                {
                    device_data: {
                        activation_timestamp: "2022-12-25T00:00:00.000000+05:00",
                        hardware_version: "v2.1",
                        manufacturer: "Garmin",
                        name: "Forerunner 945",
                        serial_number: "GR123456789",
                        software_version: "5.2.1",
                    },
                    metadata: {
                        end_time: "2022-11-24T08:00:00.000000+01:00",
                        is_nap: false,
                        start_time: "1999-11-23T22:00:00.000000+02:00",
                        timestamp_localization: 0,
                        upload_type: 1.1,
                    },
                    readiness_data: {
                        readiness: 85,
                    },
                    sleep_durations_data: {
                        sleep_efficiency: 87.5,
                    },
                    temperature_data: {
                        delta: 0.5,
                    },
                },
            ],
            type: "type",
        });
    });

    test("fetch (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/sleep").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.sleep.fetch({
                user_id: "user_id",
                start_date: 1,
            });
        }).rejects.toThrow(
            new Terra.BadRequestError({
                key: "value",
            }),
        );
    });

    test("fetch (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/sleep").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.sleep.fetch({
                user_id: "user_id",
                start_date: 1,
            });
        }).rejects.toThrow(
            new Terra.UnauthorizedError({
                key: "value",
            }),
        );
    });

    test("fetch (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TerraClient({ apiKey: "test", devId: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/sleep").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.sleep.fetch({
                user_id: "user_id",
                start_date: 1,
            });
        }).rejects.toThrow(
            new Terra.NotFoundError({
                key: "value",
            }),
        );
    });
});
