export enum ActivityType {
  "In vehicle",
  "Biking",
  "Still",
  "Unknown",
  "Tilting",
  "Walking",
  "Running",
  "Aerobics",
  "Badminton",
  "Baseball",
  "Basketball",
  "Biathlon",
  "Handbiking",
  "Mountain biking",
  "Road biking",
  "Spinning",
  "Stationary biking",
  "Utility biking",
  "Boxing",
  "Calisthenics",
  "Circuit training",
  "Cricket",
  "Dancing",
  "Elliptical",
  "Fencing",
  "American football",
  "Australian football",
  "English football",
  "Frisbee",
  "Gardening",
  "Golf",
  "Gymnastics",
  "Handball",
  "Hiking",
  "Hockey",
  "Horseback riding",
  "Housework",
  "Jumping rope",
  "Kayaking",
  "Kettlebell training",
  "Kickboxing",
  "Kitesurfing",
  "Martial arts",
  "Meditation",
  "Mixed martial arts",
  "P90X exercises",
  "Paragliding",
  "Pilates",
  "Polo",
  "Racquetball",
  "Rock climbing",
  "Rowing",
  "Rowing machine",
  "Rugby",
  "Jogging",
  "Running on sand",
  "Treadmill running",
  "Sailing",
  "Scuba diving",
  "Skateboarding",
  "Skating",
  "Cross skating",
  "Indoor rollerblading",
  "Skiing",
  "Back country skiing",
  "Cross country skiing",
  "Downhill skiing",
  "Kite skiing",
  "Roller skiing",
  "Sledding",
  "Snowboarding",
  "Snowmobile",
  "Snowshoeing",
  "Squash",
  "Stair climbing",
  "Stair climbing machine",
  "Stand up paddleboarding",
  "Strength training",
  "Surfing",
  "Swimming",
  "Swimming in pool",
  "Open water swimming",
  "Table tennis",
  "Team sport",
  "Tennis",
  "Treadmill",
  "Volleyball",
  "Beach volleyball",
  "Indoor volleyball",
  "Wakeboarding",
  "Walking fitness",
  "Nording walking",
  "Walking treadmill",
  "Waterpolo",
  "Weightlifting",
  "Wheelchair",
  "Windsurfing",
  "Yoga",
  "Zumba",
  "Diving",
  "Ergometer",
  "Ice skating",
  "Indoor skating",
  "Curling",
  "Other",
  "Crossfit",
  "HIIT",
  "Interval training",
  "Walking stroller",
  "Elevator",
  "Escalator",
  "Archery",
  "Softball",
  "Guided breathing",
}