/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Authentication } from "./api/resources/authentication/client/Client.js";
import { User } from "./api/resources/user/client/Client.js";
import { Activity } from "./api/resources/activity/client/Client.js";
import { Athlete } from "./api/resources/athlete/client/Client.js";
import { Body } from "./api/resources/body/client/Client.js";
import { Daily } from "./api/resources/daily/client/Client.js";
import { Menstruation } from "./api/resources/menstruation/client/Client.js";
import { Nutrition } from "./api/resources/nutrition/client/Client.js";
import { Sleep } from "./api/resources/sleep/client/Client.js";
import { Plannedworkout } from "./api/resources/plannedworkout/client/Client.js";
import { Integrations } from "./api/resources/integrations/client/Client.js";

export declare namespace TerraClient {
    export interface Options {
        environment?: core.Supplier<environments.TerraEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
        /** Override the dev-id header */
        devId: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the dev-id header */
        devId?: string;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class TerraClient {
    protected readonly _options: TerraClient.Options;
    protected _authentication: Authentication | undefined;
    protected _user: User | undefined;
    protected _activity: Activity | undefined;
    protected _athlete: Athlete | undefined;
    protected _body: Body | undefined;
    protected _daily: Daily | undefined;
    protected _menstruation: Menstruation | undefined;
    protected _nutrition: Nutrition | undefined;
    protected _sleep: Sleep | undefined;
    protected _plannedworkout: Plannedworkout | undefined;
    protected _integrations: Integrations | undefined;

    constructor(_options: TerraClient.Options) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "dev-id": _options?.devId,
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "terra-api",
                    "X-Fern-SDK-Version": "2.0.2",
                    "User-Agent": "terra-api/2.0.2",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get authentication(): Authentication {
        return (this._authentication ??= new Authentication(this._options));
    }

    public get user(): User {
        return (this._user ??= new User(this._options));
    }

    public get activity(): Activity {
        return (this._activity ??= new Activity(this._options));
    }

    public get athlete(): Athlete {
        return (this._athlete ??= new Athlete(this._options));
    }

    public get body(): Body {
        return (this._body ??= new Body(this._options));
    }

    public get daily(): Daily {
        return (this._daily ??= new Daily(this._options));
    }

    public get menstruation(): Menstruation {
        return (this._menstruation ??= new Menstruation(this._options));
    }

    public get nutrition(): Nutrition {
        return (this._nutrition ??= new Nutrition(this._options));
    }

    public get sleep(): Sleep {
        return (this._sleep ??= new Sleep(this._options));
    }

    public get plannedworkout(): Plannedworkout {
        return (this._plannedworkout ??= new Plannedworkout(this._options));
    }

    public get integrations(): Integrations {
        return (this._integrations ??= new Integrations(this._options));
    }
}
