/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const TerraEnvironment = {
    Default: "https://api.tryterra.co/v2",
} as const;

export type TerraEnvironment = typeof TerraEnvironment.Default;
