/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IntegrationsFetchResponse {
    providers?: string[];
    sdk_resource?: string[];
    status?: IntegrationsFetchResponse.Status;
}

export namespace IntegrationsFetchResponse {
    export type Status = "success" | "error";
    export const Status = {
        Success: "success",
        Error: "error",
    } as const;
}
