/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../../../index.js";

export interface PlannedWorkoutWriteResponse {
    user?: Terra.TerraUser;
    /** List of identifiers for the objects created, returned in the same order they were posted. I.e. Posting [ObjectA, ObjectB] will return [IdentifierA, IdentifierB] */
    log_ids?: string[];
    message?: string;
}
