/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Terra from "../../../index.js";

export interface PlannedWorkoutDeleteResponse {
    user?: Terra.TerraUser;
    processed_data?: PlannedWorkoutDeleteResponse.ProcessedData.Item[];
}

export namespace PlannedWorkoutDeleteResponse {
    export type ProcessedData = ProcessedData.Item[];

    export namespace ProcessedData {
        export interface Item {
            /** Identifier of the planned workout whose deletion was attempted */
            id?: string;
            /** Response code from the provider when attempting to delete the planned workout */
            response_code?: number;
        }
    }
}
